### ISSUE TITLE
MySQL HY000 General error: 13 Can't get stat of 

### ISSUE THREAD

**Issue by manh-nguyen** [Agence-DnD/PIMGento#10]
Hi guys,

I ran the import product and got this error:

SQLSTATE[HY000]: General error: 13 Can't get stat of '/home/www/public_html/var/import/pim/dnd_export_csv_product_2015-04-29_04_3A43_3A03.csv' (Errcode: 13)

Please help me to fix this issue 

Regards,
Manh

**Comment by manh-nguyen** [comment]
I fixed this issue by added mysql to www group and change permission to allow mysql access the folder of www. But i think it's not safe. 
And in reality, might we use an remote/external mysql server, how could we allow it read file in www folder?

**Comment by mrafulfill** [comment]
See screenshot, remote SQL server does not work, as the path does not exist. In this example MySQL Enterprise Edition runs on Windows server, hence the application is trying to look into C:\var\www, which does not exist, as suggest by mahh-ngueyen above. 

![schermafdruk 2015-05-09 15 56 29](https://cloud.githubusercontent.com/assets/4086514/7550562/0d856596-f667-11e4-81bb-b8b68f7dc541.png)

**Comment by holly-curata** [comment]
mrafulfill,
I had this issue as well but resolved. Took me a little while to work out what was going on.

The requirement for "Set local_infile mysql variable to TRUE" as listed in the Requirements List (https://github.com/Agence-DnD/PIMGento) has not been met.

1. Add local-infile=1 to the [mysql] and [mysqld] section and restart mysql service.
2. Edit the /etc/apparmor.d/usr.sbin.mysqld and add the file path of the csv files. Then restart that service as well. Refer to link below.

http://serverfault.com/questions/153769/mysql-load-data-infile-user-privilege-settings/469540#469540

**Comment by SezDevs** [comment]
Hi @magentix 

We were also seeing the file permissions error `SQLSTATE[HY000]: General error: 13 Can't get stat of...` on our servers when trying to execute Pimgento csv file imports.

We have been able to solve this by changing the database query from `LOAD DATA INFILE...` to `LOAD DATA LOCAL INFILE...` in `Pimgento_Core_Model_Resource_Request::loadDataInfile` (https://github.com/Agence-DnD/PIMGento/blob/master/app/code/community/Pimgento/Core/Model/Resource/Request.php - Line 263 at time of writing)

We found this solution here: http://dba.stackexchange.com/questions/55960/mysql-import-csv-file-error-13-hy000-cant-get-stat-of-path-file-csv-errcod

Of course, we actually created a local rewrite to apply the fix. 😄
