### ISSUE TITLE
Image cache is not automatically cleared after images import

### ISSUE THREAD

**Issue by jalogut** [Agence-DnD/PIMGento#100]
As a suggestion to optimise this issue, the following could be done:

In pimgento_image/import::cleanCache add:
- Mage::getModel('catalog/product_image')->clearCache();

It would also be nice to add a persistent counter, so the cache is only refreshed if at least a new image was added.

**Comment by magentix** [comment]
Hi jalogut,

Thanks for suggets, we will add a new option in configuration for image cache clearing :)

**Comment by magentix** [comment]
Image cache clearing can be enabled in configuration.
