### ISSUE TITLE
Import product multi-store

### ISSUE THREAD

**Issue by alexisfroger** [Agence-DnD/PIMGento#102]
Hey. Can you import product with the same website and multistore ? Because I can't assign a default value to a field with a store A and a fix value with a store B
If yes, what is the import model ? 
Thanks in advance.

**Comment by alexisfroger** [comment]
I hope this link illustrate my comments :
![image](https://cloud.githubusercontent.com/assets/15442639/11209392/127402e6-8d21-11e5-9028-df9dea887763.png)

So I have 1 website with multiples stores and storeviews. The aim is if I modiffy the storeview FR_store_A, the storeview FR_store_B keep its defaults values and dosen't overload !

**Comment by magentix** [comment]
Hi,

Wi th Akeneo, configure attributes as "scopable" and "localizable". So, column in export will be:

* attribute_1-channel_1-en_US
* attribute_1-channel_1-de_DE
* attribute_1-channel_2-en_US

Then match channel code with website code in Pimgento Configuration:

* channel_1 > website_1
* channel_2 > website_2

With this, all store with "en_US" language for "website_1" will have the correct value.
