### ISSUE TITLE
product import not removing product from categories

### ISSUE THREAD

**Issue by akkermanronald** [Agence-DnD/PIMGento#105]
We make frequent changes in Akeneo on the product > category relations. This also means that products are taken out of a category and added to other categories. Current functinality of Pimgento only adds products to categories which are in the import csv, but does not remove products from categories to which the product is already linked in Magento. As a workaround we are using product import from Commerceextensions.com (advanced dataflow) as this module has a configireable option, "append categories" yes/no. If "no" is select this removes products from all categories before adding to categories that are in the import csv. To get this working properly we are now generating a CSV (into outfile) in Akeneo MySQL, with only sku and category information (changed products only), which is imported using the above advanced dataflow profile. 

Same issue with product import re option values, if we re-import an empty value after (after deleting a value in Akeneo) this value remains "untouched" in Magento. We appreciate the complexity that comes with full catalog synchronisation, but without a reliable sync the catalog in Akeneo will soon go totally out of sync with Magento. After all, Akeneo was developed to constantly "enrich" products, it would therefore be great if this would be fully supported in future releases of Pimgento. 

Please keep up the great work! More regular replies on Github issues would be appreciated. 

Regards
Ronald

**Comment by magentix** [comment]
Hi,

Synchronization for deleted data in Akeneo (categories, products, attributes...) is not yet implemented. We work on a solution for deleting.
