### ISSUE TITLE
PIMGento for Magento 2.0 ?

### ISSUE THREAD

**Issue by kvancappel** [Agence-DnD/PIMGento#106]
Hi guys,

  first of all, thank you for this amazing solution that is PIMGento, extremely useful and practical.

  However, I have a question, unless I am mistaken, the solution is not yet compatible with Magento 2.0 and if you look at the roadmap, it's not expected soon. Can you bring me the visibility on this subject please ?

  Thank you
  
  Kévin V.

**Comment by clicktrend** [comment]
I would also like to know if there are plans to migrate to Magento 2. 

Thanks

**Comment by magentix** [comment]
Hi,

We have still no date for implementation with Magento 2. It is a subject we are discussing with the team.

**Comment by juha78** [comment]
Hi All,

Magento 2 (2.0.2) with Pimgento yet? Any solution available?
