### ISSUE TITLE
Problem associating images

### ISSUE THREAD

**Issue by buttash** [Agence-DnD/PIMGento#111]
Hi
I have image, small_image and thumbnail attributes in Magento and in Akeneo.  I have double checked and that the names are exactly the same.  

When I upload images it seems that the first image uploaded to Magento is being allocated to all three attributes.   I obviously want image mapped to image, small_image mapped to small_image etc.

I was wondering what I was doing wrong?

Hope you can help....

**Comment by buttash** [comment]
I've had the chance to look into this in more detail.  It seems that Image/Import.php allocates image, small_image and thumbnail to the first image imported:

                if ($key === 0) {
                    $data['image'] = $picture['name'];
                    $data['small_image'] = $picture['name'];
                    $data['thumbnail'] = $picture['name'];
                }

By changing this to:

                if ($key === 0) {
                    $data['image'] = $picture['name'];
                    $data['small_image'] = $picture['name'];
                    $data['thumbnail'] = $picture['name'];
                } else {
                    $attrName = basename($picture['directory']);
                    $data[$attrName] = $picture['name'];
                }

I was able to set the attributes correctly.  

That said, I'm not sure if it would be good to change the behaviour when $key === 0.  This currently results in the attribute 'image' being set to the first image read from the media/import/files for the product.  The advantage is that image is more likely to be set, the downside is that it might be a thumbnail or small_image if there is no image file.  To correct this it might be better to just remove $key altogether and have something along the lines:

                $attrName = basename($picture['directory']);
                if (strcmp($attrName, "image") == 0 ||
                    strcmp($attrName, "small_image") == 0 ||
                    strcmp($attrName, "thumbnail") == 0) {
                    $data[$attrName] = $picture['name'];
                }

**Comment by DnD-Hellion** [comment]
Hi @buttash ,
Thank you for using PIMGento.
We're glad you found a solution to your problem.
Some changes similar to the first one you described were integrated to PIMGento, it may suit your needs.

As this is an old issue, I mark it as closed.

Best regards,
