### ISSUE TITLE
Import Category issues.

### ISSUE THREAD

**Issue by softstorm22** [Agence-DnD/PIMGento#114]
Hi,

I exported the category from Akeneo and tried to import it to Magento website by using PIMagento extension.
But I got the following error. How should I solve it?
I set the permission of /var/import/pim directory to 777, but same as well.
Thanks

# pimgento_category
# category.csv
[06:03:59] tart task
[06:03:59] Task id: 566ad7cfe1869
[06:03:59] Create temporary table
[06:04:00] Step completed
[06:04:00] Insert data into temporary table
SQLSTATE[HY000]: General error: 29 File ‘/var/www/html/motostaging.dev/var/import/pim/category.csv’ not found (Errcode: 13)

**Comment by magentix** [comment]
It seems Mysql have not the right for read in "/var/www/html/motostaging.dev/var/import/pim/" directory.

In Pimgento Configuration (System > Configuration > Pimgento > General), set "CSV: Use MySql Load Data File" to "No".
