### ISSUE TITLE
Variant groups are not import into Magento by using PimGento

### ISSUE THREAD

**Issue by kvancappel** [Agence-DnD/PIMGento#116]
Hi,

  I created a configurable products in Akeneo (a variant group, for exemple : Nike Air Max (with 2 axes : color and size).

  When I export variant groups from Akeneo (Akeneo CSV Connector > Export variant groups into CSV), it works. One variant group is found. When I download the CSV and open it, I can find the name of this variant group and the 2 axes used. 

  I import this file in Magento by using PimGento, no error.

  I go into "system > configuration > pimgento > products", i choose yes for "Create configurable products", and select my two axis (color and size) into attributes of configurable products (then save ;-)).

  I go back on Akeneo, make an export of the products (csv and files with images and other files).

  First problem : I can't see my configurable product in the CSV (note : all my simples products are 100% completed, activated...)
  Second problem : I'm trying anyway to import the CSV into Magento by using PimGento, 
no error appears. But, when I go into "catalog > products, I don't find any configurable products.

  Could you help me please ?

  Thank you
  Kévin V.

**Comment by nik736** [comment]
Hi Kevin,

can you screenshot your configuration under "system > configuration > pimgento > products" for me please? I have the same issue and maybe we can find the mistake there.

Thanks
Niklas

**Comment by kvancappel** [comment]
Hi,

  here is.

![image](https://cloud.githubusercontent.com/assets/16002520/11835381/56eab906-a3d3-11e5-96e0-43b8cc78e1b3.png)

  Kévin

**Comment by nik736** [comment]
We have the exact same problem. I also don't see the configurable product in the CSV and after everything is imported I don't have a configurable product. The PIMGento setup looks more or less the same for me, maybe the mistake is that our Akeneo setup/export is not setup correctly?

**Comment by kvancappel** [comment]
Yes,

  I tried again, still the same error -_-'

  Kévin

**Comment by nik736** [comment]
Hi Kévin,

if you havn't seen the post in the Akeneo forum already. The solution is just to enable it in PIMGento.

![screen shot 2015-12-16 at 10 25 41](https://cloud.githubusercontent.com/assets/1334622/11837153/655d9d8a-a3df-11e5-95a8-c4571df72188.png)

**Comment by kvancappel** [comment]
Hi,

  thank you, it works.

  Thank you very much, really.

  Kévin

**Comment by nik736** [comment]
I have another problem, when the configurable product is created it doesn't has a name even though the variant group in Akeneo has a Attribute "Name", do you have an idea what the problem could be?

**Comment by kvancappel** [comment]
Hi,

  it's the same for me. I associated my pim_attribute_code with my magento_attribute_code (such as name), it doesn't work.

  Sorry. I will study the subject later.

  Kévin

**Comment by nik736** [comment]
Hey Kévin,

just to let you know I got it running. I looked in my CSV (variants.csv) and there was "name-de_DE" and "name-en_US" instead of name. So I just added both to "Default configurable attributes values" in PIMGento Magento settings with an empty "Value". 


Cheers
Niklas

**Comment by kvancappel** [comment]
OK, thank you.

  I will take a look.

  Kévin
