### ISSUE TITLE
Attribute_groups are imported, but no with the good name (only the akeneo_code)

### ISSUE THREAD

**Issue by kvancappel** [Agence-DnD/PIMGento#117]
Hi, 

  another question (promised, my last one).

  When I import my families and/or my attributes from Akeneo into Magento by using PimGento, I can see them into my Magento back-office, but with the wrong name. as you can see on my printscreen, I only see the "akeneo_code", not the name.

  Could you help me to fix it please ?

  Thank you
  Kévin V.

![problem_attribute_group_n1](https://cloud.githubusercontent.com/assets/16002520/11781682/bab08998-a26b-11e5-8353-39aa4007c650.png)
![problem_attribute_group_n2](https://cloud.githubusercontent.com/assets/16002520/11781683/bacee9b0-a26b-11e5-8c98-d05f69f7d969.png)

**Comment by magentix** [comment]
Hi Kevin,

Unfortunately, we have only group code in attribute export. We use this code pour create group with first letter in uppercase.
