### ISSUE TITLE
Configurable Products

### ISSUE THREAD

**Issue by buttash** [Agence-DnD/PIMGento#119]
Is there a way of setting the Magento sku for configurable products?  I'm using a pdf plugin and it would be great to be able to upload pdfs to pre-defined skus.

Thanks
Martin

**Comment by buttash** [comment]
Seems that the groups field from the product is used to create the configurable sku.  My products were configured to multiple groups, hence the comma separated sku.  Now I know how the sku is derived I will fix up my Akeneo data accordingly.

**Comment by sammarcus** [comment]
(if it is helpful to anyone else, this is because akeneo uses the terminology of variant group for a configurable equivalent)
