### ISSUE TITLE
Importing product product associations ("Crosssell","Upsell","Related Products")

### ISSUE THREAD

**Issue by magentix98** [Agence-DnD/PIMGento#120]
Dear DND Team,
in akeneo it´s possible zu define product associations. For magento there would be 3 types that are relevant: "Crosssell","Upsell","Related Products".
Is PIMGento able to import these relations? 
Best regards,
Horst

**Comment by Reflektorfalke** [comment]
Hi Magentix,

yes its possible and (partially?) supported by PIMGento.
Just make sure to name your Association Types in Akeneo as hardcoded in 
/app/code/community/Pimgento/Product/Model/Import.php

- RELATED
- UPSELL
- CROSSSELL

Please note:
Currently it seems PIMGento only supports importing associated products, 
but not associated Variant Groups (=Configurable Products in Magento).

@DnD-Team: 
Please correct me in case I am wrong or is there any way to import associated Variant Groups?
If not, any chance to have this supported soon?

Cheers

**Comment by Reflektorfalke** [comment]
For anyone not wanting to wait for "official" support for importing Variant Groups Associations:

Just add this

```
        if ($this->columnExists('RELATED-groups')) {
            $related[] = array(
                'type_id' => 1,
                'column'  => 'RELATED-groups',
            );
        }

        if ($this->columnExists('UPSELL-groups')) {
            $related[] = array(
                'type_id' => 4,
                'column'  => 'UPSELL-groups',
            );
        }

        if ($this->columnExists('CROSSSELL-groups')) {
            $related[] = array(
                'type_id' => 5,
                'column'  => 'CROSSSELL-groups',
            );
        }

```
to function  public function setRelated($task)
in /app/code/community/Pimgento/Product/Model/Import.php

Cheers

**Comment by buttash** [comment]
Hi - tried this out today and it works well.  I am intrigued why the PIMgento code uses CROSSELL and not X_SELL which is the default on the latest community release...

**Comment by magentix98** [comment]
@Reflektorfalke 
thanks a lot for the hint regarding "importing Variant Groups Associations". That´s very helpfull for me.
I was just wondering, where i can define associations betweeen variant groups in akeneo. We are on version 1.4.19 and I cannot find a tab "Associations" in "variant group" edit page. 
How did you define the associations?

**Comment by sammarcus** [comment]
@magentix98 Associations are distinct from Variant Groups and can't necessarily be associated with one another directly. You can access them here:

![image](https://cloud.githubusercontent.com/assets/8689264/13968711/34704402-f04c-11e5-9748-21711d195037.png)

Coming from the Magento world it can be hard to get the terminology right when using Akeneo (variant = configurable, family = attribute groups, etc). What are you trying to accomplish by associating these and I may be able to help from there!

**Comment by magentix98** [comment]
@sammarcus What we try to accomplish in magento words:
- we have simple products, visible in the catalog. for this products we have relations like "upsell, crosssell"
- we have configurable products (that incorporate simple products, not visible in catalog). for this configurable products we have relations for "upsell, crosssell" too

for case one, we are fine. we can use associations of different types in akeneo.
for case two, we have a problem. in my understanding "configurable products (magento)" are modelled as "variant groups (akeneo)". but we cannot make associations between "variant groups". at least I couldn´t find that feature.

I hope i was able to discribe our requirement clearly.

**Comment by sammarcus** [comment]
@magentix98 Ah, I misunderstood before. I see what you're trying to do but not sure if it is possible out-of-the-box with Akeneo. I think the underlying issue, and something I've had a hard time with, is variant groups are conceptually architected different than a configurable product. As you know, in Magento a configurable product exists on the same dimension as a simple SKU. Both have SKUs. But in Akeneo, it treats it as a group, thereby rationalizing the lack of ability to associate. I'm going to play around with it a little bit more, if I figure out how to associate these as you've described I'll let you know. Sorry I couldn't be of more help.

**Comment by Reflektorfalke** [comment]
@magentix98 and @sammarcus 
What you can do is to configure as in this screenshot:

![image](https://cloud.githubusercontent.com/assets/12202801/13997853/5475aa1a-f134-11e5-8414-314834d91efb.png)

By this the relations for configurable product in Magento will be applied follow PIMGento flow using values "from first child/simple" product.

Hope this helps for your case.

Cheers

**Comment by magentix98** [comment]
@Reflektorfalke I get your point. This could be a workaround that we can live with.
But I have a question. I can see that the associated produkt sku´s are in column "UPSELL-product". But what should be in column "UPSELL-groups"?

**Comment by buttash** [comment]
I've tried this out some more and am worried by text under the 'Default Configurable attributes value' - 

> Use the value column to force data for specific attribute. Leave empty to retrieve the value of the first simple product

Does this mean that you have to set the first simple product of a variant to have values as if it doesn't then no values will be set on the configurable, even if other simple products are set?

If the attribute takes multiple values then to take any value from the simple products would make more sense then just the first?

**Comment by magentix** [comment]
Hi,

> Does this mean that you have to set the first simple product of a variant to have values as if it doesn't then no values will be set on the configurable, even if other simple products are set?

Yes. But this solution is still adopted by Pimgento users.

Some attributes are requiered in Magento for product: description, weight, status, visibility, prices... And we must create configurable with no data (there is no way in Akeneo to set data to configurable attributes with variant).

So we have no choice to get data from the first simple product or force with static value.

If you have any other solution, propose a developpement, we'll integrate it.
