### ISSUE TITLE
Error in attribute import: "The attribute code 'weight' is reserved by system."

### ISSUE THREAD

**Issue by magentix98** [Agence-DnD/PIMGento#122]
I try to import "attribute" data from akeneo. I get the following error message:

The attribute code 'weight' is reserved by system. Please try another attribute code.

Seems like "weight" is not allowed to have in akeneo.
Is this correct? Can this be fixed?
best wishes,
hhein

**Comment by sammarcus** [comment]
@magentix98 You can have `weight` in the Akeneo PIM, but you won't be able to re-import it to Magento as Magento already has it, hence the duplicity.

Just exclude it from the rest of your attributes when you import them all into Magento.

**Comment by magentix98** [comment]
ok thanks. This means, if I need to maintain "weight" in akeneo and transfer that information to magento I will need to create another attribute for it, like i.e. "akeneo_weight", and ignore the standard "weight" attribute in magento.
correct?

**Comment by sammarcus** [comment]
It depends how you are bringing your data from Akeneo into Magento. If you are using PIMGento I believe you can match up the attributes to system ones.

**Comment by magentix** [comment]
Hi,

Right, you can match attributes data between Magento and Aekeno in configuration (system > Configuration > Catalog > Pimgento > Product > Match attributes). Example:

* akeneo_weight > weight
