### ISSUE TITLE
Linebreak in description fields of product import

### ISSUE THREAD

**Issue by magentix98** [Agence-DnD/PIMGento#123]
I have problems importing products that contain linefeeds in the description fields. The fields are enclosed by ".
The linefeeds are created in akeneo by a simple CR/LF-Button press.
There are nor errors reported during import, but there no product created in magento.
It looks like importer cannot handle the linefeeds.
How can this be solved?

**Comment by Reflektorfalke** [comment]
Hi Magentix,

guess you are using PimGento Config "CSV: Use MySql Load Data File" = "No"

For this case, adding **$enclosure = '"'** to fgetcsv() did the trick for me.
Just change Line 326
in: 
/app/code/community/Pimgento/Core/Model/Resource/Request.php
from: 
`while (($csv_line = fgetcsv($file_handle, 0, $fieldsTerminated, $fieldsEnclosure)) !== FALSE)`
to: 
`while (($csv_line = fgetcsv($file_handle, 0, $enclosure = '"', $fieldsTerminated, $fieldsEnclosure)) !== FALSE)`

(You can also try using "CSV: Use MySql Load Data File" = "No", 
but this requires MySQL FILE Permission, which is not the best idea from security perspective)

Hope this helps.

Cheers

**Comment by sammarcus** [comment]
@Reflektorfalke Can you elaborate what that option does? I struggled with my problem described in #139 and toggling this to "No" seems to have fixed some of the issues, although it came default on "Yes".

**Comment by DnD-Hellion** [comment]
Hi @magentix98 ,

Thank you for using PIMGento.
This issue was solved in [#99](https://github.com/Agence-DnD/PIMGento/issues/99).
I mark this issue as closed.

Best regards.
