### ISSUE TITLE
[Question] Grouped products support

### ISSUE THREAD

**Issue by ceckoslab** [Agence-DnD/PIMGento#126]
Hello,

I would like to ask: Is it planned to be added support of importing grouped products?

**Comment by Nesse** [comment]
It's on the roadmap but I don't know the timeline.

Compatibility with Magento >= 1.6 CE
Compatibility with Magento >= 1.10 EE
Create this type of product : Bundle, packed, virtual and downloadable products.
Think about a way to delete data

 https://github.com/Agence-DnD/PIMGento#roadmap
