### ISSUE TITLE
Please select asset attribute in Pimgento Configuration

### ISSUE THREAD

**Issue by VasyaChernets** [Agence-DnD/PIMGento#127]
Hello!
I have a little trouble .
when i import i see this:
"Please select asset attribute in Pimgento Configuration (Asset)"
![screenshot from 2016-02-23 12-47-36](https://cloud.githubusercontent.com/assets/15193807/13249261/f9dae080-da2b-11e5-8cb4-7665d80962e8.png)
how i can resolve it ?
Thanks!

**Comment by sammarcus** [comment]
@VasyaChernets did you select your **asset attribute** from the dropdown list in Asset Variation section? This is in the pimgento config panel.

![image](https://cloud.githubusercontent.com/assets/8689264/13250147/402b09ec-d9f6-11e5-9fa5-5aa56126aa6b.png)

**Comment by VasyaChernets** [comment]
Thanks !
