### ISSUE TITLE
How to sync products that were added on Magento side?

### ISSUE THREAD

**Issue by olegmack** [Agence-DnD/PIMGento#13]
Hi guys,

We have the situation when products were added on Magento side and then were migrated to PIM. 
We found that Pimgento stores relation between Magento-PIM entities in pimgento_code table, so in our case when we run the sync the Pimgento creates duplicates of products in Magento because there is no relation on that table. The obvious solution is to add such relation on Magento side, but maybe you have some recommendation for this case?

**Comment by DnD-Mimosa** [comment]
Hi,

The only solution that you have is to clear all your Magento data and re-import it with PIMGento. We also had to do this on our customer websites and there is no other solution for the moment.

Regards,
Florian.

**Comment by olegmack** [comment]
Thank you for response. Data removing is not work for us because Magento products also has information that is not stored in PIM, like:
* Magento specific attributes
* Product reviews
* Custom URL Rewrites
* Rules

Also it will not allow to use Reorder functionality and removes products from Quotes and Wishlists.
Ok, so looks like we will need to define PIM-Magento product mapping on Magento side.

**Comment by magentix** [comment]
Hello,

The solution is to complete relation between sku and entity_id in "pimgento_code" table. For product, you can use the following request:
```sql
INSERT IGNORE INTO pimgento_code (import, code, entity_id) SELECT "product", sku, entity_id FROM catalog_product_entity;
```
