### ISSUE TITLE
Configurable options - attribute code bug

### ISSUE THREAD

**Issue by buttash** [Agence-DnD/PIMGento#133]
I noticed that a lot of my products were not being updated with their size attribute.  It seems that pimgento_code uses the attribute name as prefix in the value field, e.g. for my size fields:

> '365','option','size_1000x1000x30','2688'
> '583','option','size_1000x200x30','2906'
> '453','option','size_1000x350x50_step_tread','2776'
> '202','option','size_1000x750x30','2525'
> '344','option','size_100x100x100','2667'
> '284','option','size_100x100x200','2607'

If the attribute code also includes size then the value field that I am creating (via an import application to Akeneo) looks something like this:

'6849','option','size_10_4m2_4_size_project_pack','3782'
'6812','option','size_10_75m_3_mixed_size_pack','3745'

The code in Product/Model/Import.php at 398 replaces 'size_' in order to get the code.  Unfortunately, REPLACE replaces not just the prefix, but size_ in my attribute.

To get round this I make sure I do not use size_ within the code for my size attribute.

This obviously applies to any attribute.

**Comment by magentix** [comment]
Hi,

This issue has been fixed in commit 798d7f5 ("concat" instead of "replace").
