### ISSUE TITLE
attribute codes with more than 30 characters

### ISSUE THREAD

**Issue by thomasg1311** [Agence-DnD/PIMGento#134]
we have an installation of akeneo and want to import the data of this into magento.

in akeneo we have attributes, which do have strings with more than 30 characters as code;
i was told by my magento colleagues, that magento only allows up to 30 characters for atributes...

so my questions are:
is there an (automatic) solution?
maybe already in place in akeneo / pimgento / magento?
or what would be the recommendation to handle this?

**Comment by magentix** [comment]
Hi,

There is no automatic solution. Attribute code length are 30 characters max in Magento, but there is no limit in Akeneo.

The only solution is avoid to create long code in Akeneo...
