### ISSUE TITLE
Product Import Option Code issue when option code contains attribute code

### ISSUE THREAD

**Issue by oliverde8** [Agence-DnD/PIMGento#135]
Hi, 

I have an attribute with the code brand. My options also contains the keyword brand as fallow : 
- brand_test
- brand_toto

This creates an issue because during the product import you are using REPLACE which removes both the brand of my option and the brand prefix added by the module. 

>  'FIND_IN_SET(REPLACE(`c`.`code`,"' . $columnPrefix . '_",""), `p`.`' . $column . '`)

The solution is to replace this by SUBSTRING, which will only remove the correct brand suffix

`
$prefix = $columnPrefix . '_';
$prefixL = strlen($prefix) + 1;
'FIND_IN_SET(SUBSTRING(`c`.`code`,' . $prefixL . '),`p`.`' . $column . '`)
`

I still think that it would be better if the code table contained another column to handle this.

**Comment by buttash** [comment]
Same issue as #133.  I agree with suggestion - another column make sense.

**Comment by magentix** [comment]
Hi,

Issue has been fixed. Il will be available in next release.
