### ISSUE TITLE
Product Import resets the website settings in Magento?

### ISSUE THREAD

**Issue by amitvkhajanchi** [Agence-DnD/PIMGento#137]
I have 3 websites in Magento:

* US Website
   -  US Storeview
* EU Website
    - UK Storeview
    - FR Storeview
    - ES Storeview
    - IT Storeview
    - DE Storeview
* Reseller Website
    - Reseller Storeview

In Akeneo, I have 2 Catalogs.  One is US Catalog and another is EU catalog.  The SKUs under these are unique to each respective catalog.  When I import the Categories import properly and langauges (locales) import properly to the proper storeview.  However, I do not have *any* attribute that is scopable and therefore, the attributes on export will NOT have any attribute-local-channel type heading.

When I import even a single Product thru PimGento.  The website setting that was properly organized for Search get reset to show all products on all websites (and storeviews).  This is a problem as I don't want US SKU to be shown in EU websites.

I don't know what the channel mapping is doing.  The export CSV I generate doesn't have channel data anywhere.  What do I need to do, so that US SKUs only are mapped to US website & Reseller website, and not EU products needs to be mapped to EU website.  How do I accomplish this?

Should I create a dummy attribute that is scopable for each export and simply use this to import?  Will this enable/activate the functionality to map website to channel?

Let me know!!

P.S. If nothing else, I want to disable the functionality to always reset the website setting in Magento during the import, as I can always manage the website setting in Magento as well.  But since it resets this, I am forced to then change back to the right setting each import manually.

**Comment by magentix** [comment]
Hi,

This issue has been fixed in last commit (10a962b)
