### ISSUE TITLE
Importing price for configurables with multiple axis does not work

### ISSUE THREAD

**Issue by buttash** [Agence-DnD/PIMGento#138]
The code takes the last attribute and updates the prices bases on that.  I have two axis, colour and size and the result price array for the configurable product is incorrect.

I used a variant of https://github.com/sopranobrainalliance/magento-configurable-simple which works well to solve this problem.  The current code base cannot be used.

**Comment by DnD-Hellion** [comment]
Hi @buttash ,
Thank you for using PIMGento.
As it is an old proposition and has not been supported, we close this issue.
Best regards,
