### ISSUE TITLE
import error

### ISSUE THREAD

**Issue by mrafulfill** [Agence-DnD/PIMGento#14]
We keep getting the error below:

![image](https://cloud.githubusercontent.com/assets/4086514/7549294/a6f4fb48-f62f-11e4-8a30-3ebba5a43f89.png)

Our MySQL server is not the same server as Magento, but we have also tried with Magento DB on localhost:

![image](https://cloud.githubusercontent.com/assets/4086514/7549303/e4c4e80c-f62f-11e4-82f0-ec2c98f69889.png)

**Comment by mrafulfill** [comment]
Solved by removing the port from local.xml in Magento. 

Old:

<connection>
                    <host><![CDATA[localhost:3306]]></host>
 
New:

<connection>
                    <host><![CDATA[localhost]]></host>

**Comment by magentix** [comment]
Hello,

SQL connection with specified port has been fixed.
