### ISSUE TITLE
[Question] Akeneo 1.5 and Magento 2 support

### ISSUE THREAD

**Issue by Hocdoc** [Agence-DnD/PIMGento#140]
I'm curios if PIMGento supports Akeneo 1.5 (I think so?) and Magento 2?

The README states:
- Akeneo 1.3 and 1.4
- Magento >= 1.9 CE

**Comment by magentix** [comment]
Hi Hocdoc,

Magento 2 version is under developpment, it will be available next days (stay connected).

**Comment by JulienDotDev** [comment]
Hi, what about the 1.5 compatibilty ?

**Comment by Hocdoc** [comment]
See https://github.com/Agence-DnD/PIMGento-2/issues/2 :-)

**Comment by JulienDotDev** [comment]
Sorry i forget to say that i was looking for 1.5 support with a Pimgento (1) because i'm working with magento 1 ee. My bad !
