### ISSUE TITLE
When an SKU contains a '/' the product image can't be found

### ISSUE THREAD

**Issue by hostep** [Agence-DnD/PIMGento#141]
Hi guys

We have some products in the Akeneo catalog which have an SKU which contains a `/`. Say for example: `ABC/D`.
In the exported csv file, the image field contains: `files/ABC/D/image/ABCD.jpg`

Now, when importing the csv file using PIMGento into Magento, PIMGento can't find the image file. This is because PimGento considers the first subdirectory level to always have the full SKU name of the product, which in this case isn't true.

This is using PIMGento v1.0.4

Cross referencing with issue on Akeneo, although after thinking for a while, I think they do nothing wrong, and the bug is in PIMGento itself: https://github.com/akeneo/pim-community-dev/issues/4119

Thanks!

**Comment by DnD-Hellion** [comment]
Hi @hostep ,
Thank you for using PIMGento.
Your issue seems to have been solved on the [Akeneo repository](https://github.com/akeneo/pim-community-dev/issues/4119).
I mark this issue as closed.
Best regards,
