### ISSUE TITLE
Force not to create a configurable product if a simple-product has one variant only

### ISSUE THREAD

**Issue by tom00** [Agence-DnD/PIMGento#142]
Hi,

I didn't find the possibility to select a group of products which should not have a configurable product created. Their unique feature is that they have only one variant and do not contain any axis attribute.

If I have 'Create configurable' set to yes, PIMgento is trying to create configurable products to all.

Is it possible do configure PIMGento to determine if a specific group of products should have a configurable product created and other not?

Thanks!
Tomek

**Comment by DnD-Hellion** [comment]
Hi @tom00 ,
Thank you for using PIMGento.
As it is an old proposition and has not been supported, we close this issue.
Best regards,
