### ISSUE TITLE
Blank Categories when importing

### ISSUE THREAD

**Issue by gammyduck** [Agence-DnD/PIMGento#143]
Hello, when I try to import my categories the result is this:
![](https://i.gyazo.com/fcdaf8cf795373f4063803e336aab0d3.png)

What causes this and how do I solve?

**Comment by sammarcus** [comment]
Can you share your categories CSV? Have you taken a peek at `catalog_category_entity` table to see if anything looks out of place?

**Comment by hostep** [comment]
@gammyduck: Are you using locales in Akeneo which don't exist in Magento or aren't associated to the correct storeviews (including the admin one)?

We had the same problem, using nl_BE & fr_BE locales in Akeneo, but they don't exist in Magento, so PimGento didn't know on what storeviews it should add the locale-specifc data.

You can fix it by using locales in Akeneo which are also supported in Magento, or you can rewrite the `Pimgento_Core_Helper_Data::getStoresLang` function in an extra module in Magento, so you can put your own locale-storeview mapping in there.

**Comment by gammyduck** [comment]
I just started a fresh magento install and it worked then, no idea what the issue was. Seemed likely due to a PHP 7 fix for Magento may have caused it
