### ISSUE TITLE
`FK_CAT_PRD_WS_PRD_ID_CAT_PRD_ENTT_ENTT_ID` foreign key constraint fails

### ISSUE THREAD

**Issue by clicktrend** [Agence-DnD/PIMGento#144]
Importing products fails due to `FK_CAT_PRD_WS_PRD_ID_CAT_PRD_ENTT_ENTT_ID` foreign key constraint at [step 11 "Set products to websites"](https://github.com/Agence-DnD/PIMGento/blob/master/app/code/community/Pimgento/Product/Model/Import.php#L736).

The reason is that all entries (including attributes, categories and products) in "pimgento_code" are selected to be inserted into "catalog_product_website". So there is a missing where clause to select only "products" from "pimgento_code".

**Comment by magentix** [comment]
Hi,

Thanks for this issue, we juste commit a fix.

**Comment by clicktrend** [comment]
Works. Fine
