### ISSUE TITLE
sale_price-EUR not imported

### ISSUE THREAD

**Issue by gammyduck** [Agence-DnD/PIMGento#147]
When trying to import my products, the sale_price-EUR is ignored and not imported.
I've even tried to map sale_price-EUR to sale_price but no avail.

**Comment by buttash** [comment]
Just so you know, mapping doesn't work with '-' in the field.  I have this issue when trying to get metric values into Magento.  I get over this by using sed on the csv file after it is created, e.g.

sudo sed -i'' '/;weight-unit/ s/;weight-unit/;weight_unit/' products.csv

I then can use weight_unit as required.   This might work for your price, although I suspect that there is a better way and that you need to get the mapping right with your store's currency and the price attribute name.

Martin

**Comment by gammyduck** [comment]
Ok, ill try renaming the header

**Comment by gammyduck** [comment]
... ok ive tried everything.

**Comment by gammyduck** [comment]
magento is special_price, it probably should be added to the connector?

**Comment by magentix** [comment]
Hi,

In magento, "price", "special_price" and "msrp" attributes are imposed.

So, we have 2 cases:

1. Attribute codes in PIM are "price" and "special_price". You have nothing to do.

2. Attribute codes in PIM are "sale_price" and "special_sale_price". You must match PIM attributes with Magento attributes. In configuration (System > Configuration > Catalog > Pimgento), map attributes in "Match attributes" option:
- sale_price > price
- special_sale_price > special_price
