### ISSUE TITLE
301 redirects for products (Question)

### ISSUE THREAD

**Issue by acharrex** [Agence-DnD/PIMGento#148]
The following feature appears in your README.md:

_SEO ready: 404 pages, it's over ! With PIMGento, you don't loose SEO on your product and category pages. If their names change, PIMGento create automatically a rewrite from the old URL to the new one._

Do your extension generate 301 redirects for products when their URLs are modified?

After reviewing your code, it seems that only categories are supported.

**Comment by magentix** [comment]
Hi,

For products, URL redirect is automatic with reindex process.

For tests, update manually an URL key value in "catalog_product_entity_varchar" for a product. After reindex, old URL is now redirect to new URL.

**Comment by acharrex** [comment]
Thanks for your reply!
I close the ticket.
