### ISSUE TITLE
Error during installation

### ISSUE THREAD

**Issue by e-v-medvedev** [Agence-DnD/PIMGento#149]
This string

```php
$installer->run("

ALTER TABLE 
{$installer->getTable('eav/attribute_option_value')}

ADD UNIQUE INDEX IDX_UNIQUE_PIMGENTO_OPTION_STORE (
option_id
, 
store_id
)

");
```
in …/pimgento_option_setup/mysql4-install-1.0.0.php causes error
```
Error in file: "app/code/community/Pimgento/Option/sql/pimgento_option_setup/mysql4-install-1.0.0.php" - SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '249-2'
```
Is this index realy needed?

**Comment by magentix** [comment]
Hi,

This index is needed for option import. With this index we can add or update option quickly.

In your database, you have more one option label for a store (option 249, store 2). Can you try to clean-up wrong entries in "eav_attribute_option_value" table ?

**Comment by e-v-medvedev** [comment]
This is my client's database, not my :-). And errors are the result of magmi usage :-). I hope client will be ready to pay for manual fixing of his mistakes :-).
