### ISSUE TITLE
Variant Group Attributes as source for configurable products?

### ISSUE THREAD

**Issue by tom00** [Agence-DnD/PIMGento#15]
Hi there,

Have you planned already to use the new feature in Akeneo 1.3 where a user can enter a product data to a variant group.
And then use Variant Groups CSV dump as source for creating configurable products?

Thanks,
Tomek

**Comment by IvanChepurnyi** [comment]
I also run into the same issue, but after investigation found out that PIM varian attributes are not the actual attribute values of variant, those are just setting values for all associated variations for those values. It means you cannot simply export configurable attribute values from PIM.

**Comment by magentix** [comment]
Hello,

Variant import was added in last version.
