### ISSUE TITLE
No price Attributes possible

### ISSUE THREAD

**Issue by alphalite** [Agence-DnD/PIMGento#150]
Currently it's not possible to match Akeneo Number Attributes (pim_catalog_metric, pim_catalog_number) to Magento Price, because you can't choose the price type. Will that be fixed? And if yes, can you tell me when?

**Comment by magentix** [comment]
Hi,

Price type has been added in Magento attribute types.

By default, "pim_catalog_metric" is "text". For override, add matching in "System > Configuration > Catalog > Pimgento > Attributes > Specific types":

* pim_catalog_metric > price
