### ISSUE TITLE
Attribute Set (Family) Import not working

### ISSUE THREAD

**Issue by vladstanescu** [Agence-DnD/PIMGento#154]
When trying to import the Akeneo family export, I get the following error:
`[08:31:57] Create temporary table
2 columns excepted, 4 given`

I did some digging, and found the sample family.csv which would like _code;label_ for columns.

This however would mean that I can't get the actual attribute allocations to a family from Akeneo to Magento. 

Is there a solution to this?

**Comment by magentix** [comment]
Hi,

Are you using Akeneo 1.5 ?

**Comment by vladstanescu** [comment]
Yes, we installed pim-community-standard-v1.5-latest.tar.gz

**Comment by magentix** [comment]
For compatibility with export, you must install Akeneo Connector Bundle:

https://github.com/akeneo-labs/EnhancedConnectorBundle/
