### ISSUE TITLE
[Request] Add code matching for categories

### ISSUE THREAD

**Issue by koenner01** [Agence-DnD/PIMGento#156]
If I create a category tree in Akeneo and import it into Magento with the importer, a new category tree will be created in Magento.

Upon creation of the new Magnento categories, their entity_ids will be added to the pimgento_code table (from where they will be used for future imports).

Maybe some kind of matching could be added on the Category tab in the System Configuration (like for the product attributes), where we could match the Akeneo category code with a Magento category entity_id. This way there would be freedom to re-use an existing category tree from Magento or still be able to create a total new tree.

**Comment by magentix** [comment]
Hi,

Akeneo implementation for an existing website must be doing by hand.

We have 5 kinds of import: category, family, attribute, option, product

* Category: match Akeneo code with existing category id in Magento (**entity_id** column from **catalog_category_entity**)
* Family: match Akeneo code with existing attribute set id in Magento (**attribute_set_id** column from **eav_attribute_set**)
* Attribute: nothing to do, Pimgento will fill automaticaly pimgento_code table
* Option: Match Akeneo code with existing option id (**option_id** column from **eav_attribute_option**)
* Product: Launch SQL request
```sql
INSERT IGNORE INTO pimgento_code (import, code, entity_id) SELECT "product", sku, entity_id FROM catalog_product_entity;
```
