### ISSUE TITLE
Format importing of special_date_to

### ISSUE THREAD

**Issue by gammyduck** [Agence-DnD/PIMGento#158]
Currently dates are formatted differently in Magento and Akeneo.

Akeneo is 31/05/2016
Magento is 2016-04-13 00:00:00

I can't figure out how to import special_date_to into Magento using Pimgento?

Thanks

**Comment by buttash** [comment]
I got this working by configuring pim_catalog_date => date in the attributes options for PIMgento.  I have special to/from dates populating Magento fine with this configuration.
Hope that helps
Martin

 

On 20 May 2016 at 16:04:12, gammyduck (notifications@github.com) wrote:

Currently dates are formatted differently in Magento and Akeneo.

Akeneo is 31/05/2016
Magento is 2016-04-13 00:00:00

I can't figure out how to import special_date_to into Magento using Pimgento?

Thanks

**Comment by gammyduck** [comment]
Can you show me your akeneo setup for that attribute? Should I still use "special_date_to" in Akeneo?
Thanks

**Comment by buttash** [comment]
My attribute config is:
<img width="691" alt="screen shot 2016-05-24 at 08 48 44" src="https://cloud.githubusercontent.com/assets/4323877/15496309/64567f3a-218c-11e6-83a1-942c03662f48.png">

I use 'special_to_date' in Akeneo (as that is the name of my attribute in Magento) and have set that as a Date field:
<img width="635" alt="screen shot 2016-05-24 at 08 50 55" src="https://cloud.githubusercontent.com/assets/4323877/15496370/abea13e8-218c-11e6-8ea5-4338e75921ce.png">

Hope that helps

**Comment by gammyduck** [comment]
Hello, yeah I meant special_to_date, but no luck. thanks for sharing but this didn't solve my issue unfortunately.

**Comment by buttash** [comment]
What does your date look like in the product.csv file?  My special_to_date is of the format "2016-04-07".

**Comment by gammyduck** [comment]
Magento: 2016-05-31 00:00:00

Akeneo: 31/05/2016

**Comment by gammyduck** [comment]
Cant get this working, spent all morning on it :S

**Comment by buttash** [comment]
My previous question obviously wasn't clear as you reposted your original post :o(  

I asked what the special_to_date looked like in the product.csv (or whatever you call it) export from Akeneo that you then import into Magento...

I'm no expert in this area, but it might be down to locale difference between Akeneo and Magento?  My locales are both set to en_gb.  The date from Akeneo in my product.csv is "2016-04-07" which is picked up by my PIMGento extension in Magento.  Looks like your date is formatted differently but I'm not sure where you are picking that date up.

**Comment by gammyduck** [comment]
oh right, I found this
https://i.gyazo.com/79792cc9e5f7c0e9ac580f171d476d00.png

**Comment by buttash** [comment]
The format option on the export is probably going to help...I didn't need to configure this in my environment.  Good luck.

**Comment by gammyduck** [comment]
That fixed it
