### ISSUE TITLE
Product imported missing name

### ISSUE THREAD

**Issue by manh-nguyen** [Agence-DnD/PIMGento#16]
Hi guys,

I just got a very urgent issue that the imported products are missing name.
We're using
- Akeneo EE/CE 1.3
- Magento EE 1.14
- Locale en_AU

Product data of attributes with global scope are imported to Magento successfully
Product data of attributes with non-global scope are NOT imported to Magento. Product name is an instance of this error.

We already configured 
- "Root Category" for store in "System > Manage Store"
- Default Country "Australia" in System > Configuration > General > Countries Options
- Locale "English (Australia)" in System > Configuration > General > Locale Options
- Currency "Australian Dollar" in System > Configuration > General > Currency Options
- Admin language "en_AU" in  System > Configuration > Pimgento > General
- Add website mapping "main - base" in  System > Configuration > Pimgento > General
- Configurable attributes "color" in  System > Configuration > Pimgento > Products

Here are the header:

    sku	family	groups	categories	X_SELL-groups	X_SELL-products	UPSELL-groups	UPSELL-products	SUBSTITUTION-groups	SUBSTITUTION-products	PACK-groups	PACK-products	allow_open_amount-en_AU-main	att_file1	barcode	brand	color	cost-AUD	cost_pennies-en_AU-main	country_of_manufacture-en_AU-main	custom_design-en_AU-main	custom_design_from-en_AU-main	custom_design_to-en_AU-main	custom_layout_update-en_AU-main	description-en_AU-main	gallery	genre	gift_message_available	gift_wrapping_available-en_AU-main	gift_wrapping_price-en_AU-main-AUD	giftcard_amounts-AUD	group_price-en_AU-main	image-en_AU-main	image_gallery1	image_gallery2-en_AU-main	is_recurring	is_returnable-en_AU-main	is_special	lucene_indexed	lucene_product_position	manufacturer	media_gallery	meta_description-en_AU-main	meta_keyword-en_AU-main	meta_title-en_AU-main	msrp-en_AU-main-AUD	msrp_display_actual_price_type-en_AU-main	msrp_enabled-en_AU-main	name-en_AU-main	news_from_date-en_AU-main	news_to_date-en_AU-main	open_amount_max-AUD	open_amount_min-AUD	options_container-en_AU-main	page_layout-en_AU-main	points_only	points_only_id	poppyspicks	preorder	preorder_deposit-AUD	preorder_eta_date	preorder_to_instock	preorderdescript	price-AUD	price_view	product_gotta-en_AU-main	recurring_profile	short_description-en_AU-main	small_image-en_AU-main	special_from_date	special_price-AUD	special_to_date	status-en_AU-main	tax_class_id	thumbnail-en_AU-main	tier_price-en_AU-main	url_key-en_AU-main	visibility-en_AU-main	weight-unit	enabled	weight

But all the fields with suffix -en_AU-main are not imported to Magento. I don't know why.
Please help me to check this and tell me any configuration that we missed.

Regards,
Manh

**Comment by geelweb** [comment]
Hi,

same problem for me, I removed the channel info (-main) from header columns to fix that, but we can't do that when working with crons...

**Comment by manh-nguyen** [comment]
The preg_match function is used to map the locale + website is not correct in app/code/community/Pimgento/Product/Model/Import.php .

**Comment by magentix** [comment]
Hello,

This issue has been fixed in last revision.
