### ISSUE TITLE
Price attribute

### ISSUE THREAD

**Issue by buttash** [Agence-DnD/PIMGento#160]
I'm not certain what the rationale is behind the price attribute.  I can use it to map my cost_price attribute to a cost_price attribute in Magento (pim_catalog_price_collection => price in the configuration options under Attribute) but the code to set product attribute values does not work, i.e. my cost price data does not get populated into my catalog.  By making the following code addition at line 881 to Product/Import.php I can get this to work:

```
                'cost_price' => array(
                    $costPrice . '-' . $currency,
                    $costPrice . '-' . $data['code'] . '-' . $currency,
                    $costPrice . '-' . $data['lang'] . '-' . $data['code'] . '-' . $currency,
                ),
```

Is the goal behind adding the price attribute to let people add prices in Akeneo and map them to price attributes in Magento?  If so then it is not working for me.  If there is another reason then I'd love to hear.

**Comment by DnD-Hellion** [comment]
Hi,
This issue has been resolved, we close this issue.

Best regards,
