### ISSUE TITLE
Multiselect Atttributes, only first option is choosen

### ISSUE THREAD

**Issue by alphalite** [Agence-DnD/PIMGento#161]
Hi, when I'm importing some products with multiselect Attributes, only the first value is added to the product. You got any idea what the problem could be?

Thank you

**Comment by buttash** [comment]
Hi - I have this working so know it is possible.  Is this for a configurable or simple product - I'm not sure you can do this for configurable (I'm not saying you can't, I just don't know)?  

Also, it is worth checking to make sure that all the attribute option values are set for all the values that your products can have - I've had missing values a number of times for this reason.

**Comment by alphalite** [comment]
Hi, it's for a simple product. All options are in magento and also the translations in the pim table are there. That is why I'm wondering about it. I also checked the csv and compared with the sample file.

Could there be some settings I missed to edit?

**Comment by alphalite** [comment]
I reinstalled the current Master Branch. Now It works.
