### ISSUE TITLE
Problem with attribute options import

### ISSUE THREAD

**Issue by ODLTechnology** [Agence-DnD/PIMGento#162]
Hi, 

When i tried to import the attribute's option value, i have an sql error: 
SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`eav_attribute_option_value`, CONSTRAINT `FK_EAV_ATTR_OPT_VAL_OPT_ID_EAV_ATTR_OPT_OPT_ID` FOREIGN KEY (`option_id`) REFERENCES `eav_attribute_option` (`option), query was: INSERT INTO`eav_attribute_option_value`(`option_id`,`store_id`,`value`) SELECT`tmp_pimgento_core_option`.`entity_id`AS`option_id`, 0 AS`store_id`,`tmp_pimgento_core_option`.`label-fr_FR`AS`value`FROM`tmp_pimgento_core_option`ON DUPLICATE KEY UPDATE`option_id`= VALUES(`option_id`),`store_id`= VALUES(`store_id`),`value`= VALUES(`value`)

I find the problem, the option doesn't exist in eav_attribute_option but pimgento tried to insert the value into eav_attribute_option_value.
How can i solved this problem ?

Thanks

**Comment by buttash** [comment]
I believe this can be fixed in Akeneo by assigning all of your attributes to a family.  I got this error when the family field in my attributes.csv file (or whatever you call your export file) is empty.

I have coded a fix in my local fork for which I'll create a PR - it lets you assign a family by default in the admin area.

Hope this helps
Martin

**Comment by ODLTechnology** [comment]
Thank you for your reply.

But my problem is about the options of the attribute. So in my csv, i haven't got the family, i have just the attribute code, the attribute option label and the attribute option order.

**Comment by buttash** [comment]
Sorry - misread your post. The foreign key FK_EAV_ATTR_OPT_VAL_OPT_ID_EAV_ATTR_OPT_OPT_ID makes sure that all option_ids are unique in the eav_attribute_option_vaue table.

Might be worth your while browsing tmp_pimgento_core_option to see if there are duplicate option_ids?

**Comment by ODLTechnology** [comment]
It's ok in tmp_pimgento_core_option but the query insert a value into eav_attribute_option_value but the option was not created in eav_attribute_option so the foreign key can't exist :)

**Comment by ceckoslab** [comment]
@ODLTechnology i faced the same problem. My solution was first to import all attributes and then in second import their options. 

I think that in your case you have in your CSV options for attributes that don't exist in your Magento yet.

Side note: I've run imports over a shop that functions for couple of years. So I already had product options but when I run PimGento options import it duplicated some product options. I think that this side effect will be seen in all Magento installations that are already functioning but PimGento imports started after products already existed in Magento.

**Comment by riconeitzel** [comment]
We wrote a bunch of setup scripts to prefill the pimgento_code table with matching entity_ids to solve that … I'll ask my client if it's okay to share that with you guys :-)

**Comment by DnD-Hellion** [comment]
Hi @ODLTechnology ,
Thank you for using PIMGento.

As there is no response, we close this issue.
Hope you solved your problem. :)

Best regards,
