### ISSUE TITLE
Roadmap magento 1.6

### ISSUE THREAD

**Issue by alexisfroger** [Agence-DnD/PIMGento#164]
Hey,
Do you know when the roadmap about compatibility with Magento 1.6 will release ?
Thks
Alexis

**Comment by VincentChalnot** [comment]
Hello there, I'm interested by this feature as well, any insight on when it will be implemented ?
Also, what are the problems with Magento 1.6 that would prevent us from to installing the plugin anyway ?

**Comment by DnD-Hellion** [comment]
Hi,
Thank you for using PIMGento.
As this is an old issue, we mark it as closed.

Best regards,
