### ISSUE TITLE
Running Imports from the Command Line

### ISSUE THREAD

**Issue by buttash** [Agence-DnD/PIMGento#165]
Does anyone know how to run imports from the command line?  I can execute:

`n98-magerun sys:cron:run pimdata_variant_cron`

for example, but this checks to see if the cron has been enabled (which for me I have turned off).

Ideally, I'd like to be able to run a script that imports everything I'd like.

Thanks in advance
Martin

**Comment by buttash** [comment]
I've written some shell scripts for doing this.  Unfortunately, the scripts rely upon a knowledge of where Mage.app is - since I am using modman my relative paths are different to the native location.

Happy to share this if anyone is interested.
MARTIN

**Comment by a2xchip** [comment]
@buttash Please provide it if it is possible

**Comment by buttash** [comment]
You can find the code here: https://github.com/buttash/PIMGento/blob/WEB-122/shell/pimgentoImport.php

**Comment by a2xchip** [comment]
@buttash Thank you very much! :+1:

**Comment by magentix** [comment]
Hi,

Script from @buttash will be added in next release.
