### ISSUE TITLE
Multiple Asset Attributes

### ISSUE THREAD

**Issue by alphalite** [Agence-DnD/PIMGento#168]
How is it possible to import Akeneo EE Assets from multiple Attributes? You just can Choose one in Pimgento Settings Page.

**Comment by DnD-Hellion** [comment]
Hi @alphalite ,
Thank you for using PIMGento.

This feature is not possible as is in PIMGento.

Therefore, we would recommand you to develop a specific rewrite of the module, adapted to your needs.

I mark this issue as closed.

Best Regards,
