### ISSUE TITLE
Multi Store Support?

### ISSUE THREAD

**Issue by sgrover** [Agence-DnD/PIMGento#170]
Does PIMGento support multi-store configurations?  i.e. Store one is the main store and receives all product details from Akeneo.  Store Two is a sub store showing just a list of products relevant to that store (but exists in the main store).  We understand that would mean we will need to give Akeneo some knowledge of what stores we have set up in Magento (custom code, creative use of attributes, etc.).

Our current export from Akeneo / import to Magento routine is removing the products from Store 2 (cuz the store column only has the main store for those products).  PIMGento is being implemented to shift away from the manual (via cron) task of export/import.  But we still have this multi store issue to resolve.

Thanks for any insights.

**Comment by avinashsamala** [comment]
HI 
can you any one explain how to import products from Akeneo to multi store magento 2.
thanks,

**Comment by DnD-Hellion** [comment]
Hi @sgrover ,
Thank you for using PIMGento.
Maybe your solution was in [this issue](https://github.com/Agence-DnD/PIMGento/issues/118).
You can also check the Akeneo documentation about [localizing your PIM](https://docs.akeneo.com/cookbook/localization/index.html).
Could you please come back to us if you need any further detail ?
Hope this helps !

Hi @avinashsamala ,
Thank you for using PIMGento. (I reckon you are using [PIMGento2](https://github.com/Agence-DnD/PIMGento-2))
Please check the link above for your Akeneo configuration.
For any problem encountered using our extension with Magento 2, you may open a new issue on the [PIMGento-2 extension issue section](https://github.com/Agence-DnD/PIMGento-2/issues) ?
Hope you find a solution there. ;)

Best regards.

**Comment by DnD-Hellion** [comment]
Hi @sgrover ,
Thank you for using PIMGento.
Maybe your solution was in [this issue](https://github.com/Agence-DnD/PIMGento/issues/118).
You can also check the Akeneo documentation about [localizing your PIM](https://docs.akeneo.com/cookbook/localization/index.html).
Could you please come back to us if you need any further detail ?
Hope this helps !

Hi @avinashsamala ,
Thank you for using PIMGento. (I reckon you are using [PIMGento2](https://github.com/Agence-DnD/PIMGento-2))
Please check the link above for your Akeneo configuration.
For any problem encountered using our extension with Magento 2, you may open a new issue on the [PIMGento-2 extension issue section](https://github.com/Agence-DnD/PIMGento-2/issues) ?
Hope you find a solution there. ;)

Best regards.

**Comment by Dnd-Gimix** [comment]
Hi @avinashsamala ,

As @DnD-Hellion said, please check the PIMGento2 repository for more informations regarding Magento 2.

Hi @sgrover ,

As this issue is very old and has not been answered, I'll close it.
Feel free to open a new one if necessary ;-)

I wish you both a great day !

Regards,
