### ISSUE TITLE
Clean attributes product value with empty value

### ISSUE THREAD

**Issue by Raphael-johanne** [Agence-DnD/PIMGento#174]
Hi,

I would like clean some attributes product values (description for example) but when i send an empty value, the current value is not replaced. In the code, I found this in agencednd/module-pimgento/Entities/Model/ResourceModel/Entities.php

`
public function setValues($tableName, $entityTable, $values, $entityTypeId, $storeId, $mode = 1)
{
 ...

 if ($connection->tableColumnExists($tableName, $value)) {
  $select->where('TRIM(`' . $value . '`) <> ?', new Expr('""'));
 }
 ...
}
`

So the value cound not be replaced if empty is send.

How can I replace current value with empty value ?

Thanks in advance !

**Comment by dardanKG** [comment]
https://github.com/Agence-DnD/PIMGento/commit/438ed9db23d296d4156c2633b8007a512b1d2d09#diff-6c23bcd2c8dda9d16a681f3630d4efde

**Comment by DnD-Hellion** [comment]
Hi @Raphael-johanne ,

Thank you for using PIMGento.

As it is an old proposition and has not been supported, we close this issue.

Best regards,
