### ISSUE TITLE
Magento 1.9.3

### ISSUE THREAD

**Issue by alobeejay** [Agence-DnD/PIMGento#175]
There seems to be problems with the extension on Magento 1.9.3. We have another instance with 1.9.2.4 and it works there.
With 1.9.3 on the other hand when clicking on "Catalog->Import PIM Data" an empty white page occurs and the following PHP error message gets thrown:

PHP Fatal error:  Call to a member function getParams() on null in /...../app/code/community/Pimgento/Core/Block/Adminhtml/Launcher.php on line 20

**Comment by seblepers** [comment]
I do confirm this issue.

**Comment by seblepers** [comment]
This is due to Flash support drop.
More [details here](http://magento.stackexchange.com/questions/140550/security-patch-supee-8788-possible-problems).

**Comment by alobeejay** [comment]
Thanks for digging into this!
Is PIMGento still in development? Any chances that this gets fixed?

**Comment by seblepers** [comment]
I just proposed a pull request :
https://github.com/Agence-DnD/PIMGento/pull/177

**Comment by magentix** [comment]
Hi,

Now refer to the branch "magento-1.9.3". This branch fix compatiblity problem for Magento >= 1.9.3.

**Comment by convenient** [comment]
@magentix Will this branch ever be tagged? It's kind of hard to run `composer update agence-dnd/pimgento` otherwise?

**Comment by SezDevs** [comment]
Hi @magentix 
Following on from @convenient 's previous comment, please could you create a release for branch `magento-1.9.3` then we can composer update your module?
Many thanks!

**Comment by DnD-Merlin** [comment]
Hi @convenient, @SezDevs,
we have just create the tag `1.1.1` for Magento 1.9.3 version https://github.com/Agence-DnD/PIMGento/releases/tag/1.1.1
