### ISSUE TITLE
PIMGento stuck on "Waiting for Task" [1.9.3.1]

### ISSUE THREAD

**Issue by gammyduck** [Agence-DnD/PIMGento#178]
I have updated using the new branch to fix the errors.
However as a result PIMGento now gets stuck for me like so:
![f2d463f8a9cf51cbd35ced2d1e381303 1](https://cloud.githubusercontent.com/assets/3619746/20521526/84d2117e-b0a3-11e6-83a0-c49ef5a6026c.png)

**Comment by gammyduck** [comment]
Any way I can show more information to help resolve this?

**Comment by buttash** [comment]
You can turn on Chrome developer tools and look to see if there are any errors…Click on the three vertical buttons on the far right of the toolbar, More Tools -> Developer Tools...

On 29 November 2016 at 20:10:41, gammyduck (notifications@github.com) wrote:

Any way I can show more information to help resolve this?

**Comment by DnD-Hellion** [comment]
Hi @gammyduck ,

Thank you for using PIMGento.

As no response has been given for a long time, we close this issue.

Best regards,
