### ISSUE TITLE
Problem with accents

### ISSUE THREAD

**Issue by Luc-Nematis** [Agence-DnD/PIMGento#18]
Special characters and accents are not interpreted correctly when importing into temporary tables.

To correct the problem, I modified the import request of the `Pimgento_Core_Model_Resource_Request :: loadDataInfile` method with this:

```php
$query = "LOAD DATA INFILE '" . $file . "' REPLACE
              INTO TABLE " . $this->getTableName($name) . "
              CHARACTER SET utf8 
              FIELDS TERMINATED BY '" . $fieldsTerminated . "'
              OPTIONALLY ENCLOSED BY '\"'
              LINES TERMINATED BY '" . $linesTerminated . "'
              IGNORE 1 LINES;";
```

(Note de "CHARACTER SET utf8")

**Comment by geelweb** [comment]
`LOAD DATA INFILE` use the database encoding if not specified, as Magento create utf8 table, your db shoud have utf8 encoding. You can check with this query

    SELECT * FROM information_schema.SCHEMATA S WHERE schema_name = "YOUR-DB-NAME";

if you see something else than "utf8", you can try to update like this (don't forget to backupt your db before alter)

    ALTER DATABASE your_db_name DEFAULT CHARACTER SET utf8;

This solve the pb for me.

**Comment by antoineguigan** [comment]
Maybe this should be added to the README ?

**Comment by magentix** [comment]
Hello,

Indeed, database encoding must be UTF-8. Readme has been updated.
