### ISSUE TITLE
Magento 1.9.2 / Akeneo 1.6

### ISSUE THREAD

**Issue by Seospan** [Agence-DnD/PIMGento#182]
Hi !
We have a doubt in the compatibility of Pimgento with our client's system : 

-The readme talks about compatibility with Magento >=1.9.3, but the requirements says "Magento >= 1.9 CE"... what about 1.9.2 ?
-We work with Akeneo 1.6, there's a post in the issues saying "PimGento is compatible with PIM 1.6, but it is not written in the README doc.", so it should be ok with 1.6 ?

In short : will it work with Pimgento + Magento 1.9.2 + Akeneo 1.6 ?

Thanks a lot and great work by the way ! :D

**Comment by DnD-Hellion** [comment]
Hi @Seospan ,

Thank you for your interest in PIMGento.

The last version of PIMGento are is compatible with Magento >= 1.9 and Akeneo >= 1.3, so no worries on your side using 1.9.2. ;)

I close this issue.

Best regards,
