### ISSUE TITLE
Categories not appear after import

### ISSUE THREAD

**Issue by anakinsolo** [Agence-DnD/PIMGento#186]
Hello,

It seems that the categories did not appear in Catalog->Manage Categories after importing categories. Although, it appears that I have a new category, without any name. From the Manage Stores ->  Root Category, alongside Default Category, I have a new, blank category (without name) also.

I am using Magento 1.9.3 and Akeneo 1.6, the csv files are the ones in the sample folder.

**Comment by magentix** [comment]
Hi,

In your categorie import file, are **label** column localized?

*Example:*

For **label-en_US**, store must be defined with **en_US** in local configuration.

Admin default language must also be in **en_US** ("general/locale/code" path in "core_config_data" table).

**Comment by anakinsolo** [comment]
Hi, thanks. I figured it out. My magento locale setting is Finnish and the Akeneo was English
