### ISSUE TITLE
Attributes imports fail

### ISSUE THREAD

**Issue by Luc-Nematis** [Agence-DnD/PIMGento#19]
When I import the attributes, I get the following error:

"Excepted columns 14, 15 given".

This is the code of the method Pimgento_Attribute_Model_Import :: createTable ():

```php
$this->getRequest()->createTableFromFile($this->getCode(), $file, 14);
```

If I remove the "14" setting (which is not present in other import classes), it passes. For cons, I get an error when indexing data:

```
SQLSTATE [23000]: Integrity constraint violation: 1452 Can not add or update a child row: a foreign key constraint fails (`magento`.` # sql-1_17e`, CONSTRAINT` FK_CAT_PRD_FLAT_2_ENTT_ID_CAT_PRD_ENTT_ENTT_ID` FOREIGN KEY (`entity_id`) REFERENCES` catalog_product_entity` (`entity_id`) ON DELETE CASCADE ON UPDATE CCAC)
```

_Note that I had to change the export bundle attributes Akeneo since the attributes of labels his hard-coded in the code (https://github.com/Agence-DnD/DnD-MagentoConnectorBundle/issues/27) to take the set in 4 languages ​​Akeneo and Magento._

**Comment by jalogut** [comment]
I have exactly the same error but with 13 columns instead:

"Excepted columns 14, 13 given".

I am using the default example data in Akeneo

**Comment by antoineguigan** [comment]
Exports have a variable number of columns, due to the translations. Maybe the check over the number of columns should be removed ?

**Comment by Reflektorfalke** [comment]
Having the same issue while playing with Akeneo sample data: 14 columns excepted, 13 given.

When exporting attributes using the DnD Connector I get the following 13 columns:

type;code;label-en_US;label-fr_FR;group;unique;useable_as_grid_filter;allowed_extensions;metric_family;default_metric_unit;localizable;scopable;families

The missing column seems to be label-de_DE.
As cross-check, when exporting same data using Akeneo csv Connector, I get the following 13 columns, includung column label-de_DE (but missing the families):

type;code;label-de_DE;label-en_US;label-fr_FR;group;unique;useable_as_grid_filter;allowed_extensions;metric_family;default_metric_unit;localizable;scopable

Removing the number of columns check sounds indeed like a good idea, considering the number of label-* columns can vary depending on number of translations/storeviews.

Cheers

**Comment by magentix** [comment]
Hello,

Attributs columns limitation has been fixed.
