### ISSUE TITLE
SQLSTATE[21000]: Cardinality violation: 1242 Subquery - Double product entry

### ISSUE THREAD

**Issue by Phoenixtourist414** [Agence-DnD/PIMGento#190]
SQLSTATE[21000]: Cardinality violation: 1242 Subquery returns more than 1 row, query was: UPDATE `pigeontmp_pimgento_core_product` t SET `entity_id` = ( SELECT`entity_id` FROM `pigeonpimgento_code` c WHERE t.`code` = c.`code` AND c.`import` = "product" )

I'm having alot of trouble with this error, there is barely any documentation or support for this extension so I'm going to try post it here:

=> Whatever we try, we keep getting this Cardinality violation: 1242 error, basically it seems to be adding these items double in the pimgento_code table. We tried searching all over the web for 2 months now and the only thing we found was to truncate that table, this however will cause us to double add all products which is again, not a solution.

Question: can somebody please give us some help with this? We can also hire your aid via Upwork or Freelancer if need be.

Additional info:
- dedicated vps
- ubuntu 14.04
- mysql 5.5
- Magento 1.9 (multisite)

**Comment by buttash** [comment]
Hi

I've experienced this kind of thing before and tracked it to a null value.  I'm not saying that this is the problem for you but  I suggest you use Mysqladmin to look at the tmp table to see what the column values for code are. You can then manually delete rows from tmp and run the SQL to find what row in the tmp table is causing the problem. 

Martin

**Comment by Phoenixtourist414** [comment]
Hello buttash, thank you for sharing.
But in which column are we to search, there seem to be alot of null values. 

Basically what is happening on our side is that we can import 1 channel perfectly into the Magento 1.9. The problems arise after this: table(pimgento_code)
- When importing the next category it will add all products double to these tables
- When resyncing category and attributes, same happens, all are added double 

I will attempt what you've just mentioned,
Thank you

**Comment by buttash** [comment]
I'd look at the column named 'code' as that is the one that is being used to extract rows for the update.

**Comment by Phoenixtourist414** [comment]
I called with a Belgium company, they mentioned there is a double export issue in the 1.5 version of Akeneo so we had it installed entirely again in version 1.6.

It can synchronise now, only thing is that it is not filling in the correct locales. I have labels with 'default everywhere now'.

**Comment by DnD-Hellion** [comment]
Hi @Phoenixtourist414 ,

Thank you for using PIMGento.

We hope you solved your issue locales. PIMGento automatically uses locale codes to map your Akeneo locales with Magento store views.
Maybe this could help : https://help.akeneo.com/articles/manage-your-locales.html

As this is an old issue, I mark it as closed.

Best regards,
