### ISSUE TITLE
Documentation for Pimgento! Question about implementation with Magento.

### ISSUE THREAD

**Issue by ljseals** [Agence-DnD/PIMGento#199]
Greetings,
I am having several issues with implementing Pimgento with Magento. These issues may be very easy but the lack of documentation has caused me to delay deployment of my website. I have installed both modules with composer and both are working after troubleshooting some initial problems with the extensions. 

1. Issue one: Upon product import, the products are not enabled on the website.
I have watched the initial video on youtube several times and it seems that you have to map the products to attributes to Magento attributes; however, if you are new to Akeneo and Magento this is not straight forward.

2. Issue two: Implementation of import variant or import asset variation is not explained.
Maybe these are new features but the video nor the installation guide gives clarity to the purpose of these functions.

3. Issue three: Import images from Akeneo to Magento is not explained.
It shows that you must upload the images to media/import/files/ directory but how do you get them from Akeneo after placing them in media for a product.

4. Issue four: Stock update is not explained.
Akeneo allows for an attribute of stock quantity; however, pimgento states to upload CSV with 2 columns: sku and qty. Can this be explained so that a person new to Akeneo would understand?

Lastly, I thank the Lord for touching your hearts to develop this open source extension and provide it free as you could have kept it in house. If anyone can explain the above issues or point me to documentation that I may research it will be appreciated. God bless you!

Salutations,
J'ai plusieurs problèmes avec la mise en œuvre de Pimgento avec Magento. Ces problèmes peuvent être très simples, mais le manque de documentation m'a fait retarder le déploiement de mon site. J'ai installé les deux modules avec le compositeur et les deux fonctionnent après avoir dépanné quelques problèmes initiaux avec les extensions.

1. Problème un: lors de l'importation du produit, les produits ne sont pas activés sur le site.
J'ai regardé la vidéo initiale sur youtube à plusieurs reprises et il semble que vous devez mapper les produits aux attributs aux attributs Magento; Cependant, si vous êtes nouveau chez Akeneo et Magento, cela ne se déroule pas.

2. Problème deux: la mise en œuvre de la variante d'importation ou de la variation de l'actif d'importation n'est pas expliquée.
Peut-être que ce sont de nouvelles fonctionnalités, mais la vidéo et le guide d'installation donnent une clarté au but de ces fonctions.

3. Numéro trois: Importer des images d'Akeneo vers Magento n'est pas expliqué.
Il montre que vous devez télécharger les images dans les médias / import / fichiers / répertoire, mais comment les obtenir d'Akeneo après les avoir placés dans les médias pour un produit.

4. Problème 4: la mise à jour du stock n'est pas expliquée.
Akeneo permet un attribut de la quantité de stock; Cependant, pimgento déclare télécharger CSV avec 2 colonnes: sku et qty. Cela peut-il être expliqué afin qu'une personne nouvelle d'Akeneo comprenne?

Enfin, je remercie le Seigneur de toucher vos cœurs pour développer cette extension open source et la fournir gratuitement, car vous pourriez l'avoir gardé dans la maison. Si quelqu'un peut expliquer les problèmes ci-dessus ou m'indiquer à la documentation que je pourrais faire, il sera apprécié. Dieu te bénisse!

**Comment by buttash** [comment]
Hi

1.  You'll need to map Akeneo 'enabled' to status in the PIMGento configuration > Products.  Under Default configurable attributes values map 'enabled' to 1 to enable configurables

2.  This is fairly straightforward once you remember to set the attribute to be used for variants. 
 Under the attibute (size/color etc) set 'Default configurable attributes values' as yes.

3.  I use rsync between Akeneo and my Magento host.  Works fine

4.  I don't use stock, so cannot help there.

Bon chance :o)

**Comment by ljseals** [comment]
Thanks Butttash,
Is there anyway you can share a screenshot of the options that you have set in Pimgento configuration. I have these options set and I am unable to see any products.

![pimgento](https://user-images.githubusercontent.com/25220839/27787935-31e0d1ea-5fac-11e7-923a-b185aff122a8.jpg)

Also you said I use rsync between Akeneo and my Magento host. Works fine
I do not think it will be a problem to implement this but were do I find the product images in Akeneo. What local folder to I rsync to my magento host. Thanks!

**Comment by buttash** [comment]
Perhaps it is better if you let me have an email address and then I can send you through some more config info.

**Comment by ljseals** [comment]
@buttash  Thanks my e-mail address is ljseals@outlook.com
