### ISSUE TITLE
Prefix on table

### ISSUE THREAD

**Issue by ghost** [Agence-DnD/PIMGento#205]
Hi,

I report a bug : 
On my agento I got a prefix on my tables.
So when I want to import ly product with asset, pimgento search the pimgento_asset table.
But in the bdd, the table is prefixed like this prefix_pimgento_asset.
So it didn't find the table, report me an error and dont import my asset on my product :/

So in quick fixe, I hardcoded the prefix into `app/code/community/Pimgento/Product/Model/Import.php` like
```
         if (!$adapter->isTableExists('myprefix_pimgento_asset')) {
                 $task->setMessage('Table pimgento_asset doesnot exist');
                 return false;
         }
```
Then I execute the product import and I got an other error :
```
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'bdd_magento.pimgento_asset' doesn't exist
```
Again, the prefix is missing.

**Comment by borriglione** [comment]
Maybe this is related to https://github.com/Agence-DnD/PIMGento/commit/be3d899a42c6e09d4d3630f40dc71569cd8d8b97 and `$adapter->getTableName()` is used instead of  `$resource->getTable()` is used

**Comment by DnD-Hellion** [comment]
Hi,

This issue has been solved.

I close this issue.

Best regards,
