### ISSUE TITLE
Create configurable products by default

### ISSUE THREAD

**Issue by ng-s** [Agence-DnD/PIMGento#210]
Hi, 

I would like to create configurable products by default. In fact I don't want to create variant in the PIM, I would like to create variant only in Magento. 
I tried by creating the attribute _type and set configurable but it doesn't work during the import. 
Do you have an idea how I can do that ? 
Thanks

**Comment by DnD-Hellion** [comment]
Hi @ng-s ,

Thank you for using PIMGento.

Configurable product creation in Magento is strictly linked to the Akeneo variant functionnality in PIMGento.
Therefore, we would recommand you to develop a specific rewrite of the module, adapted to your needs, so PIMGento can take this attribute into account.

I mark this issue as closed.

Best regards,
