### ISSUE TITLE
Wrong function "getDefaultAttributSetId" on Attribute import

### ISSUE THREAD

**Issue by barig** [Agence-DnD/PIMGento#213]
Hi everyone,

I updated Pimgento to version 1.3.2.b today and I faced a fatal error : Call to undefined method Pimgento_Attribute_Model_Import::getDefaultAttributSetId() line 89.

It is caused by commit 3c76afff1d64009443d7875ab05d49b5c51b6e6c, it adds a function getProductEntityTypeId and calls a function $this->getDefaultAttributSetId().

I will make a pull request right after my issue is opened.

**Comment by barig** [comment]
Pull request is done, it can be found here #214 .

**Comment by riconeitzel** [comment]
can be closed, eh?

**Comment by barig** [comment]
Yes it has been merged right after I opened the issue.

Sorry for the late answer and thank you for your quick merge !
