### ISSUE TITLE
CSV Files with UTF8-BOM fail importing

### ISSUE THREAD

**Issue by kanduvisla** [Agence-DnD/PIMGento#215]
If a CSV file happens to have a UTF8-BOM, the file fails to import. The message is:

    Column "sku" not found

Even thought the `sku`-column is present in the CSV file

**Comment by Dnd-Gimix** [comment]
Hi @kanduvisla ,

Thank you for using PIMGENTO.
As your pull request has been accepted, we are closing this issue.

Best regards,
