### ISSUE TITLE
Fatal error: Uncaught Error: Call to a member function toOptionArray() on boolean in /home/directmailboxes/public_html/app/code/core/Mage/Adminhtml/Block/System/Config/Form.php

### ISSUE THREAD

**Issue by jlotty22** [Agence-DnD/PIMGento#218]
I am getting this error when trying to get to System > Configuration > Catalog > Pimgento

`Fatal error: Uncaught Error: Call to a member function toOptionArray() on boolean in /home/directmailboxes/public_html/app/code/core/Mage/Adminhtml/Block/System/Config/Form.php:463 Stack trace: #0 /home/directmailboxes/public_html/app/code/core/Mage/Adminhtml/Block/System/Config/Form.php(229): Mage_Adminhtml_Block_System_Config_Form->initFields(Object(Varien_Data_Form_Element_Fieldset), Object(Mage_Core_Model_Config_Element), Object(Mage_Core_Model_Config_Element)) #1 /home/directmailboxes/public_html/app/code/core/Mage/Adminhtml/Block/System/Config/Form.php(164): Mage_Adminhtml_Block_System_Config_Form->_initGroup(Object(Varien_Data_Form), Object(Mage_Core_Model_Config_Element), Object(Mage_Core_Model_Config_Element)) #2 /home/directmailboxes/public_html/app/code/core/Mage/Adminhtml/Block/System/Config/Edit.php(92): Mage_Adminhtml_Block_System_Config_Form->initForm() #3 /home/directmailboxes/public_html/app/code/core/Mage/Adminhtml/controllers/System/ConfigController.php(107): Mage_Adminhtml_Block_System_Config_Edit->ini in /home/directmailboxes/public_html/app/code/core/Mage/Adminhtml/Block/System/Config/Form.php on line 463`

I am running Magento 1.9.3.0 and initially installed the Master branch, then saw the issue with the Flash uploader and installed the Pimgento-magento-1.9.3 branch, which fixed the uploader section, but the config section is broken. I'm not sure if this is a bug or if it is due to installing the Master branch first.

Any help would be appreciated!  Thanks!

**Comment by DnD-Hellion** [comment]
Hi @jlotty22 ,

Thank you for using PIMGento.

This error has been fixed in a previous version.

I mark this issue as closed.

Best regards,
