### ISSUE TITLE
Source Model pimgento_asset/system_config_source_connexionType missing

### ISSUE THREAD

**Issue by riconeitzel** [Agence-DnD/PIMGento#219]
Source Model is referenced in corresponding system.xml https://github.com/Agence-DnD/PIMGento/blob/12260e076c6179da365b9e4ffe524bcb5a4248e8/app/code/community/Pimgento/Asset/etc/system.xml#L77

But it's missing in the directory. Can't create PR cause I don't know what it should return :D 

Seems to be a mixture of connexion (credentials?!) and connexion_type (the current connexion)?

**Comment by riconeitzel** [comment]
PR provided https://github.com/Agence-DnD/PIMGento/pull/220

**Comment by riconeitzel** [comment]
PR for master provided as well: #221

**Comment by DnD-Tuk** [comment]
Hello @riconeitzel and thanks for contributing! PR's have been merged.
