### ISSUE TITLE
Stuck on "Match PIM code with entity"

### ISSUE THREAD

**Issue by holly-curata** [Agence-DnD/PIMGento#22]
I'm trying to run imports through the admin importer and is stalling when trying to "Match PIM code with entity"

Can someone please advise what this issue might relate to?

**Comment by holly-curata** [comment]
![screen shot 2015-05-16 at 8 47 41 am](https://cloud.githubusercontent.com/assets/4299274/7663089/462c31e0-fba8-11e4-8f36-ba6ec713310d.png)

**Comment by magentix** [comment]
Hello,

You can open the debug tool of your browser and access the network tab. Check response of the request for step "Match PIM code with entity".

**Comment by holly-curata** [comment]
Thanks for that. I did what you suggested but it didn't tell me anything.

Then I realised the Magento I'm working with is 1.7.0.2 and your requirements state 1.9+. Is there any way to get PIMGento working with earlier versions of CE or do I need to upgrade?

**Comment by magentix** [comment]
Hello,

the module does not yet work with versions of Magento less than 1.9. The compatibility is planned in the roadmap. We will work on the compatibility soon.

**Comment by holly-curata** [comment]
Hi Matthieu,
Thanks for your reply. No problem, I worked that out in the end by testing with a clean version of 1.9 and it worked well.

Do you have any estimate for compatibility with earlier versions of Magento?
