### ISSUE TITLE
Category Path empty

### ISSUE THREAD

**Issue by riconeitzel** [Agence-DnD/PIMGento#222]
after importing categories all path fields are empty (breaks reindex, breaks frontend)

**Comment by DnD-Hellion** [comment]
Hi @riconeitzel ,

Thank you for using PIMGento.

Could please tell us if you still encounter this problem ? Could you give us more details on the procedure you followed and the eventual errors ?

Looking forward to reading you. :)

**Comment by riconeitzel** [comment]
hi @DnD-Hellion,

unfortunately our client stopped using akeneo for now. So I don't know if it's still an issue.

I gonna close this issue and if we continue with the project I'll reopen it, if needed.

Thanks,
Rico
