### ISSUE TITLE
How to use the same image for image small_image Thumbnail

### ISSUE THREAD

**Issue by ng-s** [Agence-DnD/PIMGento#225]
Hi, 

How to use the same image for the main image, the small image and the Thumbnail in magento ? 

Thanks,

**Comment by DnD-Hellion** [comment]
Hi @ng-s ,

Thank you for using PIMGento.

Could you please specify is your issue is related to Magento configuration or to PIMGento imports ?

Looking forward to reading you. :)

**Comment by Dnd-Gimix** [comment]
Hi @ng-s ,

As this issue is very old and has not been answered, I'll close it.
Feel free to open a new one if necessary ;-)

Have a good day.

Regards,
