### ISSUE TITLE
On import product SQLSTATE[HY000] [2002] No such file or directory

### ISSUE THREAD

**Issue by GuilleretFlorian** [Agence-DnD/PIMGento#226]
Hi,

All other import work well. But when I try to import product on step 7 i got this message : 

SQLSTATE[HY000] [2002] No such file or directory.

Here is the trace : 

`{"0":"SQLSTATE[HY000] [2002] No such file or directory","1":"#0 \/var\/www\/magento2\/vendor\/magento\/zendframework1\/library\/Zend\/Db\/Adapter\/Pdo\/Mysql.php(111): Zend_Db_Adapter_Pdo_Abstract->_connect()\n#1 \/var\/www\/magento2\/vendor\/magento\/framework\/DB\/Adapter\/Pdo\/Mysql.php(398): Zend_Db_Adapter_Pdo_Mysql->_connect()\n#2 \/var\/www\/magento2\/vendor\/magento\/framework\/DB\/Adapter\/Pdo\/Mysql.php(545): Magento\\Framework\\DB\\Adapter\\Pdo\\Mysql->_connect()\n#3 \/var\/www\/magento2\/vendor\/magento\/framework\/DB\/Adapter\/Pdo\/Mysql.php(580): Magento\\Framework\\DB\\Adapter\\Pdo\\Mysql->_query('SELECT `pimgent...', Array)\n#4 \/var\/www\/magento2\/vendor\/magento\/zendframework1\/library\/Zend\/Db\/Adapter\/Abstract.php(756): Magento\\Framework\\DB\\Adapter\\Pdo\\Mysql->query(Object(Magento\\Framework\\DB\\Select), Array)\n#5 \/var\/www\/magento2\/vendor\/magento\/framework\/Model\/ResourceModel\/Db\/AbstractDb.php(348): Zend_Db_Adapter_Abstract->fetchRow(Object(Magento\\Framework\\DB\\Select))\n#6 \/var\/www\/magento2\/vendor\/magento\/framework\/Model\/AbstractModel.php(536): Magento\\Framework\\Model\\ResourceModel\\Db\\AbstractDb->load(Object(Pimgento\\Log\\Model\\Log), '5a5238de0a528', 'identifier')\n#7 \/var\/www\/magento2\/vendor\/agencednd\/module-pimgento\/Log\/Observer\/PimgentoImportStepFinishObserver.php(39): Magento\\Framework\\Model\\AbstractModel->load('5a5238de0a528', 'identifier')\n#8 \/var\/www\/magento2\/vendor\/magento\/framework\/Event\/Invoker\/InvokerDefault.php(72): Pimgento\\Log\\Observer\\PimgentoImportStepFinishObserver->execute(Object(Magento\\Framework\\Event\\Observer))\n#9 \/var\/www\/magento2\/vendor\/magento\/framework\/Event\/Invoker\/InvokerDefault.php(60): Magento\\Framework\\Event\\Invoker\\InvokerDefault->_callObserverMethod(Object(Pimgento\\Log\\Observer\\PimgentoImportStepFinishObserver), Object(Magento\\Framework\\Event\\Observer))\n#10 \/var\/www\/magento2\/vendor\/magento\/framework\/Event\/Manager.php(66): Magento\\Framework\\Event\\Invoker\\InvokerDefault->dispatch(Array, Object(Magento\\Framework\\Event\\Observer))\n#11 \/var\/www\/magento2\/generated\/code\/Magento\/Framework\/Event\/Manager\/Proxy.php(95): Magento\\Framework\\Event\\Manager->dispatch('pimgento_import...', Array)\n#12 \/var\/www\/magento2\/vendor\/agencednd\/module-pimgento\/Import\/Model\/Factory.php(86): Magento\\Framework\\Event\\Manager\\Proxy->dispatch('pimgento_import...', Array)\n#13 \/var\/www\/magento2\/vendor\/agencednd\/module-pimgento\/Import\/Controller\/Adminhtml\/Import\/Run.php(59): Pimgento\\Import\\Model\\Factory->execute()\n#14 \/var\/www\/magento2\/generated\/code\/Pimgento\/Import\/Controller\/Adminhtml\/Import\/Run\/Interceptor.php(24): Pimgento\\Import\\Controller\\Adminhtml\\Import\\Run->execute()\n#15 \/var\/www\/magento2\/vendor\/magento\/framework\/App\/Action\/Action.php(107): Pimgento\\Import\\Controller\\Adminhtml\\Import\\Run\\Interceptor->execute()\n#16 \/var\/www\/magento2\/vendor\/magento\/module-backend\/App\/AbstractAction.php(229): Magento\\Framework\\App\\Action\\Action->dispatch(Object(Magento\\Framework\\App\\Request\\Http))\n#17 \/var\/www\/magento2\/vendor\/magento\/framework\/Interception\/Interceptor.php(58): Magento\\Backend\\App\\AbstractAction->dispatch(Object(Magento\\Framework\\App\\Request\\Http))\n#18 \/var\/www\/magento2\/vendor\/magento\/framework\/Interception\/Interceptor.php(138): Pimgento\\Import\\Controller\\Adminhtml\\Import\\Run\\Interceptor->___callParent('dispatch', Array)\n#19 \/var\/www\/magento2\/vendor\/magento\/module-backend\/App\/Action\/Plugin\/Authentication.php(143): Pimgento\\Import\\Controller\\Adminhtml\\Import\\Run\\Interceptor->Magento\\Framework\\Interception\\{closure}(Object(Magento\\Framework\\App\\Request\\Http))\n#20 \/var\/www\/magento2\/vendor\/magento\/framework\/Interception\/Interceptor.php(135): Magento\\Backend\\App\\Action\\Plugin\\Authentication->aroundDispatch(Object(Pimgento\\Import\\Controller\\Adminhtml\\Import\\Run\\Interceptor), Object(Closure), Object(Magento\\Framework\\App\\Request\\Http))\n#21 \/var\/www\/magento2\/vendor\/magento\/framework\/Interception\/Interceptor.php(153): Pimgento\\Import\\Controller\\Adminhtml\\Import\\Run\\Interceptor->Magento\\Framework\\Interception\\{closure}(Object(Magento\\Framework\\App\\Request\\Http))\n#22 \/var\/www\/magento2\/generated\/code\/Pimgento\/Import\/Controller\/Adminhtml\/Import\/Run\/Interceptor.php(39): Pimgento\\Import\\Controller\\Adminhtml\\Import\\Run\\Interceptor->___callPlugins('dispatch', Array, NULL)\n#23 \/var\/www\/magento2\/vendor\/magento\/framework\/App\/FrontController.php(55): Pimgento\\Import\\Controller\\Adminhtml\\Import\\Run\\Interceptor->dispatch(Object(Magento\\Framework\\App\\Request\\Http))\n#24 \/var\/www\/magento2\/vendor\/magento\/framework\/Interception\/Interceptor.php(58): Magento\\Framework\\App\\FrontController->dispatch(Object(Magento\\Framework\\App\\Request\\Http))\n#25 \/var\/www\/magento2\/vendor\/magento\/framework\/Interception\/Interceptor.php(138): Magento\\Framework\\App\\FrontController\\Interceptor->___callParent('dispatch', Array)\n#26 \/var\/www\/magento2\/vendor\/magento\/framework\/Interception\/Interceptor.php(153): Magento\\Framework\\App\\FrontController\\Interceptor->Magento\\Framework\\Interception\\{closure}(Object(Magento\\Framework\\App\\Request\\Http))\n#27 \/var\/www\/magento2\/generated\/code\/Magento\/Framework\/App\/FrontController\/Interceptor.php(26): Magento\\Framework\\App\\FrontController\\Interceptor->___callPlugins('dispatch', Array, Array)\n#28 \/var\/www\/magento2\/vendor\/magento\/framework\/App\/Http.php(135): Magento\\Framework\\App\\FrontController\\Interceptor->dispatch(Object(Magento\\Framework\\App\\Request\\Http))\n#29 \/var\/www\/magento2\/generated\/code\/Magento\/Framework\/App\/Http\/Interceptor.php(24): Magento\\Framework\\App\\Http->launch()\n#30 \/var\/www\/magento2\/vendor\/magento\/framework\/App\/Bootstrap.php(256): Magento\\Framework\\App\\Http\\Interceptor->launch()\n#31 \/var\/www\/magento2\/index.php(39): Magento\\Framework\\App\\Bootstrap->run(Object(Magento\\Framework\\App\\Http\\Interceptor))\n#32 {main}","url":"\/44980admin\/pimgento\/import\/run\/key\/61210c98a872ba86bc2788b3adf392e31900e6d6b7a8e2d22f813ff833fb5988\/?isAjax=true","script_name":"\/index.php"}`

I try to launch with bin/magento or with magento back office but i got the same issue.

We are on magento 2.2.2 CE and Akeneo 2.0.6 CE mysql version 5.7.20

I try to launch manually the next step ( 8 ) and it works.

Can you help me on that ?

**Comment by DnD-Hellion** [comment]
Hi @GuilleretFlorian ,

Thank you for using PIMGento.

As you are using Magento 2, this issue is on the wrong extension repository.

Could you please expose your problem anew on the PIMGento-2 extension issue section : https://github.com/Agence-DnD/PIMGento-2/issues ?

See you there. ;)

I mark this issue as closed.

Best regards.
