### ISSUE TITLE
Is the module compatible with Magento 2.2.x ?

### ISSUE THREAD

**Issue by amenk** [Agence-DnD/PIMGento#235]
o.T. :-)

**Comment by DnD-Hellion** [comment]
Hi @amenk ,

Thanks for using PIMGento. For Magento 2.x, please check the PIMGento2 repository: [https://github.com/Agence-DnD/PIMGento-2](https://github.com/Agence-DnD/PIMGento-2).

You will also find the compatibility informations there: [https://github.com/Agence-DnD/PIMGento-2/blob/master/doc/important_stuff/compatibility.md](https://github.com/Agence-DnD/PIMGento-2/blob/master/doc/important_stuff/compatibility.md). PIMGento2 is fully compatible with Magento 2.2.x.

Hope this helps. ;)

Best regards,
