### ISSUE TITLE
Import product Too many columns

### ISSUE THREAD

**Issue by QuentinSc** [Agence-DnD/PIMGento#242]
Hello,

product import for a french retailler.
Error mysql

![image](https://user-images.githubusercontent.com/16439299/52577266-04743080-2e22-11e9-92b6-3d8ee8261b11.png)

Could you help us ?

Thank you !

**Comment by DnD-Mimosa** [comment]
Hi @QuentinSc,

I think you'll find the answer here ==> https://github.com/Agence-DnD/PIMGento-2/blob/master/CHANGELOG.md#10011---2016-11-03.

BR,
Florian.

**Comment by QuentinSc** [comment]
I forgot to mention that we are using the Pimgento 2 API Module, this changelog is related to Pimgento API ?

**Comment by DnD-Mimosa** [comment]
Hi @QuentinSc,

Could you please open this issue in the correct repository please ? (https://github.com/Agence-DnD/PIMGento-2-API/issues)

In the same time, could you close this issue ?

Thank you very much !

BR,
Florian.
