### ISSUE TITLE
Problem with metric Akeneo attribute

### ISSUE THREAD

**Issue by Luc-Nematis** [Agence-DnD/PIMGento#25]
Hello,

The name of the attributes of type "metric" is exported with dash suffix (ex: "weight-").

When importing in Magento, these attributes are ignored.

**Comment by emishusta** [comment]
I have the same problem with "metric" attributes.
Also, there is problem with "price" attributes: it is exported with currency "current_cost-USD", but on imporing to magento it doesn't update values.

**Comment by Luc-Nematis** [comment]
For now, I have solved the problem as follows:

I modified the method `Pimgento_Core_Model_Resource_Request :: _ formatField ()`:

```php
    protected function _formatField($field)
    {
        return trim(trim(str_replace(PHP_EOL, '', preg_replace('/\s+/', ' ', trim($field))),'"'), '-');
    }
```

I then created the same method in `Pimgento_Product_Model_Import` and I call for in each loop on the columns of the CSV file:

* `Pimgento_Product_Model_Import::updateValues`
* `Pimgento_Product_Model_Import::setValues`

```php
$columns = $this->getRequest()->getFirstLine($file);
//...
foreach ($columns as $column) {
    $column = $this->_formatField($column);
    //...
}
```

and it's work.
