### ISSUE TITLE
Configurable attributes of simple products are erased on configurable product update

### ISSUE THREAD

**Issue by antoineguigan** [Agence-DnD/PIMGento#26]
Steps : 

- create a variant group on the PIM
- set the "name" attribute as an attribute of the configurable product in the PIMGento configuration
- export the products to PimGento
- change the name of the product in PimGento
- export the products to PimGento

Result : 

The configurable attributes of the simple products have been erased.

**Comment by linslin** [comment]
Same issue here. @magentix could you help?

**Comment by linslin** [comment]
reopen please
