### ISSUE TITLE
Not import price and missing product name in Catalog->Product list

### ISSUE THREAD

**Issue by dominicnguyen810** [Agence-DnD/PIMGento#29]
Hi guys!

I have configure the "name" and "price" attribute in the PIM as Channel and Localizable.
![2015-05-25_10-20-18](https://cloud.githubusercontent.com/assets/10016971/7877961/bc68ce32-060b-11e5-8139-c45aa71d8036.png)

Then, I have exported products to CSV file with header format below:
![2015-05-29_14-08-18](https://cloud.githubusercontent.com/assets/10016971/7878008/52e4db3a-060c-11e5-9d8e-df5f32073245.png)

Pim config:
![2015-05-29_14-18-56](https://cloud.githubusercontent.com/assets/10016971/7878129/b42bd640-060d-11e5-9582-50399fa7ab72.png)

### Result:
1. Missing product name in product list:
![2015-05-29_14-11-31](https://cloud.githubusercontent.com/assets/10016971/7878050/c5dab10a-060c-11e5-9d82-14970e42426b.png)

but display in product details:
![2015-05-29_14-12-25](https://cloud.githubusercontent.com/assets/10016971/7878051/c776744a-060c-11e5-8702-a766cf26c4f0.png)
2.  Not import price:
![2015-05-29_14-13-28](https://cloud.githubusercontent.com/assets/10016971/7878058/e6b0cf40-060c-11e5-80a7-666d92590768.png)

I think only an error with attributes as Channel and Localizable, attributes as Global still work.
Please check it.

**Comment by DnD-Mimosa** [comment]
Hi @dominicnguyen810,

Are you using the last version of PIMGento ? In fact, this problem has been fixed 2 days ago.

If you're using the last version, can you tell me if you configured well your Magento by creating one store view per language and set the good language for your store view in System > Configuration > General > General ?

Regards,
Florian.

**Comment by dominicnguyen810** [comment]
Hi @DnD-Mimosa,

I'm using latest version of Pimgento and set "English (Australia)" language, "en_AU" locale for "base" store.
I also tried with Magento CE 1.9.1.1 fresh version, but not work.

Can you change Scope and Localizable of "name" attribute in Akeneo as below:
![2015-05-25_10-20-18](https://cloud.githubusercontent.com/assets/10016971/7905366/8b431488-0841-11e5-803a-439833bd1a1d.png)
and export products from Akeneo to CSV file, then import it to Magento?

I think only an error with attributes as Channel and Localizable, attributes as Global still work.

**Comment by magentix** [comment]
Hello,

We just publish a release for fix this problem. You can use the last version of PIMGento.
