### ISSUE TITLE
Conditions on import

### ISSUE THREAD

**Issue by margus** [Agence-DnD/PIMGento#32]
Hello,

is there a way to have conditions on product import, that when the product is being created for the first time then it will have status disabled and when it's being updated then it will not update the status of the product?

**Comment by magentix** [comment]
Hi margus,

Product attribute must be in Akeneo. For exemple, an attribute "enable" can be added in Akeneo, and be matched in Pimgento with "status" attribute from Magento.

**Comment by margus** [comment]
Hello,

That part I know how to map the attributes in akeneo > pimgento but the question was is there some way to define the default values on products for example when you import them for the first time, say it dosnt have a status(enabled set in akeneo or is set enabled but as it's created for the first time then it should always have the status disabled in magento
