### ISSUE TITLE
Variant cron is keep on failing in magento Pimgento

### ISSUE THREAD

**Issue by maramkoteswar** [Agence-DnD/PIMGento#33]
Good Morning,

We’re trying to import variant group data from Akeneo into Magento using the PimGento cron configuration.
We’re able to import variant groups manually (via Catalog à Import Pim Data à Select Pim: Import Variant).
 
However, the cron job to import the data automatically is failing. Here is the log file extract:
 
2015-06-23T07:54:02+00:00 INFO (6): pimgento_variant : /var/www/magentocp/var/import/
2015-06-23T07:54:02+00:00 INFO (6): [00:54:02] Task id: 5589109a40048
2015-06-23T07:54:02+00:00 INFO (6): [00:54:02] Create temporary table
2015-06-23T07:54:02+00:00 ERR (3): Cannot create table without columns comments
 
The file we’re trying to import via cron has the following contents:
code;axis;label-en_US;label-fr_FR;type
reebok_sport_sani_socks;color,manufacturer,size;"Reebok Sport Sani Socks";"Reebok Sport Sani Socks";VARIANT
bauer_vapor_sr_x700_hockey_sticks;grip,orientation;"Bauer Vapor SR x700 Hockey Sticks";"Bauer Vapor SR x700 Hockey Sticks";VARIANT
 
Any idea why this is happening and how to trouble shoot this?
Please help me on this.

Thanks & Regards,
Koteswar Maram

**Comment by magentix** [comment]
Hi Koteswar,

Have you the same problem with other imports ? This step create columns in tmp table with CSV informations. All imports use this method. Your CSV is correct.

**Comment by maramkoteswar** [comment]
Hi Magentix,

The other imports were working fine,except this variant group, as already mentioned we don't have option to use the DND-Connector bundle to export to remote server,so we have written separate script to move the same file to remote server.But still getting the same "Cannot create table without columns comments"every time while enabled the cron for variant in magento.
Please let us know the way forward.

Thanks,
Koteswar Maram

**Comment by holly-curata** [comment]
Hi, did this get resolved? Also experiencing the exact same issue. Also, all other imports that I've tested so far working fine.

**Comment by Nik736** [comment]
I've the same issue, how did you resolve this?

**Comment by e-v-medvedev** [comment]
Faced the same issue when trying to import categories or attributes.  Magento version 1.9.4.2. For the test, the file was used, supplied with the module as test data.

**Comment by e-v-medvedev** [comment]
On page /index.php/admin/task/index/ i got error:

[Tue Sep 10 11:58:06.984193 2019] [proxy_fcgi:error] [pid 23527] [client 127.0.0.1:55198] AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught Error: Call to a member function getParams() on null in /app/code/community/Pimgento/Core/Block/Adminhtml/Launcher.php:18\nStack trace:\n#0 /app/code/core/Mage/Core/Model/Layout.php(491): Pimgento_Core_Block_Adminhtml_Launcher->__construct(Array)\n#1 /app/code/core/Mage/Core/Model/Layout.php(437): Mage_Core_Model_Layout->_getBlockInstance('Pimgento_Core_B...', Array)\n#2 /app/code/community/Pimgento/Core/Block/Adminhtml/Task.php(18): Mage_Core_Model_Layout->createBlock('pimgento_core/a...')\n#3 /app/code/core/Mage/Core/Block/Abstract.php(297): Pimgento_Core_Block_Adminhtml_Task->_prepareLayout()\n#4 /app/code/core/Mage/Core/Model/Layout.php(456): Mage_Core_Block_Abstract->setLayout(Object(Mage_Core_Model_Layout))\n#5 /index.php/admin/system_config/index/key/bda1f92b89ef8aaaf7b1ca8eacee77e4/
