### ISSUE TITLE
Importing issues

### ISSUE THREAD

**Issue by buttash** [Agence-DnD/PIMGento#34]
I am running Magento 1.9 on Amazon AWS and have configured Akeneo to drop off files into /var/import.  Browse files under Catalog-> Import PIM Data opens up the web browser which means I am unable to access the data pushed to the server.

I then copied the files from my Akeneo server to my local computer.  I used browse to select the file followed by upload.  When I executed I got:

# pimgento_attribute
# attributes.csv
[12:19:46] Start task
[12:19:46] Task id: 558fd852949e4
[12:19:46] Create temporary table
[12:19:46] Step completed
[12:19:46] Insert data into temporary table
SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Name or service not known

I cannot find any log information to work out what is happening.  The Magento instance I am using is from Bitnami if that helps....

Hope you can help!

Regards
Martin

**Comment by magentix** [comment]
Hello,

Can you give us your host node in local.xml ? (config->global->resource->default_setup->connection->host)

Regards,
Matthieu

**Comment by buttash** [comment]
Hi Matthieu

The problem seems related to the Bitnami Magento environment.  I have spun up a standard Ubuntu server and performed a compete manual install and have successfully imported data into Magento.  One item that I found I had to add before getting the import to work was to grant file permissions to the Magento MySql user.  Not sure if that is a general issue or particular to my install.

I’m now having to rework my attribute names to get them to match Magento - is there was way to do this through PIMGento? 

Regards
Martin

**Comment by magentix** [comment]
Hello,

In configuration, (system > Configuration > Catalog > Pimgento > Products), you can match Akeneo attributes with Magento Attributes. For exemple:

Pim Attribute : enabled / Magento Attribute : status

Regards,
Matthieu

**Comment by sammarcus** [comment]
@buttash how specifically did you grant the file permissions to the mysql user? I am having the same issue:
SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Name or service not known
![image](https://cloud.githubusercontent.com/assets/8689264/14058959/6905c134-f307-11e5-803c-68bddf9ba307.png)
 Thank you so much!!

**Comment by buttash** [comment]
I didn’t as I am running on a shared server where I cannot access apparmor - I therefore added some code to read from a csv file and import line by line.  If you have sudo privileges then suggest you look for help here http://askubuntu.com/questions/451584/mysql-on-ubuntu-14-04-problem-with-apparmor-permissions-for-data-directory <http://askubuntu.com/questions/451584/mysql-on-ubuntu-14-04-problem-with-apparmor-permissions-for-data-directory>

Alternatively, try changing the configuration of PIMgento - reading a CSV file line by line is fine for me as I do not have a large catalog.

Martin
