### ISSUE TITLE
SQLSTATE[28000]: Invalid authorization specification: 1045 Access denied for user 

### ISSUE THREAD

**Issue by Nik736** [Agence-DnD/PIMGento#35]
Hi,

I am trying to import Categories, this is the log:

----------------------------------------------------------------------
# pimgento_category
# export_2015-06-29_07_53_40_2.csv
[10:58:12] Start task
[10:58:12] Task id: 559108a45ffb3
[10:58:12] Create temporary table
[10:58:12] Step completed
[10:58:12] Insert data into temporary table
SQLSTATE[28000]: Invalid authorization specification: 1045 Access denied for user 'dbuser'@'IP_OF_LOCAL_IP' (using password: YES)
----------------------------------------------------------------------

The problem here is, that I use an external Database server, but PIMGento either always uses the local IP to try to connect to the DB or it always shows the local IP? How can I change it to use the external DB server?

**Comment by magentix** [comment]
Hello,

Pimgento use "core_write" by default for insert data in tmp table. In file "app/code/community/Pimgento/Core/Model/Resource/Request.php", you can change connexion name at line 387 (_query method).

Regards,
Matthieu

**Comment by Nik736** [comment]
Hi Matthieu,

thanks for your reply.

I've changed the $host variable, but it's still the same error.

My Magento installation uses the external Database server, why is PIMGento even trying to use the local IP address? Is there anything else I can do to get it working?

Thanks!

**Comment by Nik736** [comment]
Anyone? :(

**Comment by magentix** [comment]
Hi Nik,

In "app/code/community/Pimgento/Core/Model/Resource/Request.php", can you try to manually update connexion ?

``` php
$dsn  = 'mysql:host=' . $host[0] . ';dbname=' . $connConfig->dbname;
if (isset($host[1])) {
    $dsn .= ';port=' . $host[1];
}
        
$pdo = new PDO($dsn, $connConfig->username, $connConfig->password, $options);
```
Try to change with custom variables:
``` php
$dsn  = 'mysql:host=X.X.X.X;dbname=myDbName'; // Here
if (isset($host[1])) {
    $dsn .= ';port=' . $host[1];
}
        
$pdo = new PDO($dsn, 'USERNAME', 'PASSWORD', $options); // And here
```

**Comment by Nik736** [comment]
Hi,

thanks! I did that, but it's the same error, it still tries to connect to the localhost DB server which doesn't exist.

**Comment by jcpla** [comment]
Hello, I had the same problem and manage to resolve it by:  
- install package php5-mysqlnd. It will automatically remove php5-mysql. (on Debian apt-get install php5-mysqlnd)
- In https://github.com/Agence-DnD/PIMGento/blob/master/app/code/community/Pimgento/Core/Model/Resource/Request.php#L255 , add "LOAD DATA LOCAL INFILE"

A little patch would be really appreciated ;)
Thanks in advance

**Comment by Nik736** [comment]
Hi,

thanks, but this doesn't solve the problem as well :(

I tried to move the site to another server where the DB server runs locally (and mysqlnd is used), the issue is still the same. It just throws the same error with the local IP.

**Comment by jcpla** [comment]
if you check your grant permissions 
-select * from information_schema.user_privileges where grantee like '%dbuser%' ; have you the privilege for file to YES for your user/ip ?

The temp config can be :
- GRANT ALL PRIVILEGES ON *.* TO 'dbuser'@'%' IDENTIFIED BY 'dbPwd' WITH GRANT OPTION;
=> it allowed connection for db use from any servers.

Hope that's it

**Comment by linslin** [comment]
While the import is running, PIMGento creates a "temporary" table in your Database. Grant right "DBManager" .... does fix it for me. 

Cheers.

**Comment by ToonSpinISAAC** [comment]
What solved this for me, was granting the server FILE option to my database user with:

    GRANT FILE ON *.* TO 'insert_db_username_here'@'localhost';

Fortunately, where I work, we have complete control over the servers on which our Magento sites run, but I doubt that this option is granted by default on shared hosting providers.

Creating a PDO instance and then doing a `LOAD DATA INFILE` feels a bit weird to me, especially if this requires special server privileges. Why was this done, is it because of performance, or perhaps to be able to easily do large product imports?

**Comment by annapivniak** [comment]
@ToonSpinISAAC Thanks! It helped me too

**Comment by gideonp** [comment]
Thank you sir, @ToonSpinISAAC..
