### ISSUE TITLE
Importing Product Custom Options

### ISSUE THREAD

**Issue by nbinnendijk** [Agence-DnD/PIMGento#36]
Hi,

Akeneo does not seem to support Product custom options, but proposes to handle them as dedicated text fields.

Question: do you plan to implement a solution to enable support of product custom options import?

Something like:
In Akeneo, using Akeneo recommendation to use text fields, but defining that it must contains a json like structure to represent product custom options:
ex: 
{
    title : {
        label : xxxx;
        language : FR;
    }
    Input_type: dropdown;
    Is Required : Yes;
    Sort Order : 0;
    Options : {
        item {
            title : {
                label : xxxx;
                language : FR;
            };
            price : 10;
            price_type: ...
            sku : ...
            sort_order : ...
        };
        item {
           ....
        };
    }
}
    

In PIMGento: for the text fields set as Product Custom Options by configuration, importing them as such instead of importing them as Product attributes values.

**Comment by nbinnendijk** [comment]
Forgot to say: Thanks in advance for your feedback :-)

**Comment by magentix** [comment]
Hello Nicolas,

Custom option import is not yet implemented. We will add this feature in roadmap (certainly for august or september).

Regards,
Matthieu
