### ISSUE TITLE
Attributes Export - Wrong Locales

### ISSUE THREAD

**Issue by holly-curata** [Agence-DnD/PIMGento#39]
Hi there,
I have a single locale, English (Australia) in Akeneo (code: en_AU). 

All export profiles are correctly exporting the data for that locale, except for the attributes export profile which is exporting columns for en_US and fr_FR only, neither of which are being used.

I am using Akeneo version 1.3.17 and Pimgento 2.2.3 (I think?). I upgraded pigmento last week so it's a recent version of Pimgento codebase.

**Comment by magentix** [comment]
Hello,

The problem come from Akeneo Export.

Add issue to MagentoConnectorBundle project (https://github.com/Agence-DnD/DnD-MagentoConnectorBundle)
