### ISSUE TITLE
Insert data into temporary table error

### ISSUE THREAD

**Issue by manh-nguyen** [Agence-DnD/PIMGento#4]
Hey guys,

Magento ver. 1.14.1.0
I got this issue when trying to import attribute

pimgento_attribute
 dnd_export_csv_attributes2015-04-20_12_3A04_3A26_7.csv
[01:08:55] tart task
[01:08:55] Task id: 5534b4177ff70
[01:08:55] Create temporary table
[01:08:55] Step completed
[01:08:55] Insert data into temporary table
SQLSTATE[HY000]: General error: 29 File 'C:\xampp\mysql\data\xampphtdocsmagentoee114varimportpimdnd_export_csv_attributes2015-04-20_12_3A04_3A26_7.csv' not found (Errcode: 2)

Regards,
Manh

**Comment by christophednd** [comment]
Hello,
the problem is fixed.
You can download v1.0.1. https://github.com/Agence-DnD/PIMGento/releases/tag/1.0.1
Regards
Christophe
