### ISSUE TITLE
Admin value of attribute option

### ISSUE THREAD

**Issue by mrafulfill** [Agence-DnD/PIMGento#41]
Why is the attribute option admin value not the same as the attribute option code in Akeneo?

See below for current situation:
- Akeneo attribute:
![akeneo attribute](https://cloud.githubusercontent.com/assets/4086514/8730590/08a5f214-2bf2-11e5-945a-3b5000893cc6.png)

- Result in Magento:
![result magento](https://cloud.githubusercontent.com/assets/4086514/8730601/1cc9f894-2bf2-11e5-9c35-887c2d3ee3e9.png)

- CSV from Akeneo to Magento:
![csv pimgento](https://cloud.githubusercontent.com/assets/4086514/8730608/2bd05086-2bf2-11e5-9234-8db98cb59fa1.png)

The attribute option code in Akeneo is used in the product export to Magento and this works ok.

However, the attribute option admin value should normally be stored in the eav_attribute_option_value table in Magento under store_id = 0. Currently the translated value is inserted into the admin value.

**Comment by clicktrend** [comment]
+1

**Comment by bhouillon** [comment]
I have the same problem, so it doesn't map correctly. And all the select and multiselect options are not set in product import...

**Comment by magentix** [comment]
Default admin value is currently setted with local value. This configuration is suitable for most users.

But this can be updated in Import model for option, example:

```php
foreach ($ids as $storeId) {

    $options = $adapter->select()
        ->from(
        $this->getTable(),
            array(
                'option_id' => 'entity_id',
                'store_id'  => $this->_zde($storeId),
                // START:UPDATED
                'value'     => $storeId == 0 ? 'code' : 'label-' . $local
                // END:UPDATED
            )
        );

        $insert = $adapter->insertFromSelect(
            $options,
            $resource->getTable('eav/attribute_option_value'),
            array('option_id', 'store_id', 'value'),
            1
        );

    $adapter->query($insert);

}
```
