### ISSUE TITLE
Simple select option value not set when channelname in CSV

### ISSUE THREAD

**Issue by mrafulfill** [Agence-DnD/PIMGento#43]
When the channelname is included in the CSV the simple select options values are not set. When the channel name is removed from the CSV everything works fine and simple select values are set correctly. 

![select values not filled](https://cloud.githubusercontent.com/assets/4086514/8731295/aa153f3e-2bf6-11e5-98e4-bb521ba99d0a.png)

**Comment by bhouillon** [comment]
Hi, have you found a solution to this problem, because whatever I do, select and multiselect values are not set correctlly. Thanks in advance

**Comment by mrafulfill** [comment]
Yes, as a workaround you can remove the channelname from the CSV and it should work.

**Comment by magentix** [comment]
Hi,

Channel for option is not yet supported. We work on it :)

**Comment by mrafulfill** [comment]
Thx. We will "watch this space" for an update. In the meantime, is there an easy way to remove the channel name from the export? (instead of manually editing the CSV each time)?
