### ISSUE TITLE
attribute export with attribute type price not working

### ISSUE THREAD

**Issue by mrafulfill** [Agence-DnD/PIMGento#44]
If attribute type in Akeneo is set to price, the attribute import will create a new attribute in Magento with type "text field". If a price attribute is manually created in Magento with attribute type price the import of prices will not succeed. The same issues applies to the native Magento attribute MSRP (manufacturer suggested retail price). Values for MSRP cannot be imported. This is probably related to the fact that only price and special price are hard coded.

![price hard coded](https://cloud.githubusercontent.com/assets/4086514/8731625/e9e1908e-2bf8-11e5-8168-66f9c869df54.PNG)

**Comment by magentix** [comment]
Hi,

Indeed, "price" and "special_price" have specific traitement. For this attributes, we must manage currency.

If attribute code is not "price" or "speical_price" in Akeneo, you can match values in configuration:

![price](https://cloud.githubusercontent.com/assets/346889/9608419/87c2ade8-50ce-11e5-8e61-51a35a3a39e4.jpg)

**Comment by mrafulfill** [comment]
Agree with Linslin. This issue should not have been closed. MSRP is a native Magento price attribute and should be included as price attribute in the code snippet above.
