### ISSUE TITLE
Encoding issue on special chars

### ISSUE THREAD

**Issue by nbinnendijk** [Agence-DnD/PIMGento#45]
Hi,

when importing families (for ex) that contain special chars in the label, the result contain encoding issues.

Ex : importing "générique", getting "gÃ©nÃ©rique" in the backend

File encoding is UTF-8.

Thx in advance,
Nicolas

**Comment by linslin** [comment]
UTF-8 ist supported fine. Check your table and database Collation and also do "SET NAMES 'utf8' in mysql.
