### ISSUE TITLE
%datetime% in local path causes problems

### ISSUE THREAD

**Issue by buttash** [Agence-DnD/PIMGento#47]
If the local file path has %datetime% then the report does not seem to get uploaded.

**Comment by magentix** [comment]
Files uploaded by Cron must have a fixed name.

**Comment by buttash** [comment]
Not sure I understand the response.  

From memory (the issued was posted over a month ago), the file being uploaded did not have a %datetime% - this was fixed.  Despite this, the upload failed due to the local name not being fixed.  

If this is a feature then that's fine, but I'm not sure where this is covered in the documentation.
