### ISSUE TITLE
Issue Importing Products

### ISSUE THREAD

**Issue by holly-curata** [Agence-DnD/PIMGento#49]
NOTE: CLIENT IMPLEMENTATION

Further to the following topic: https://github.com/Agence-DnD/PIMGento/issues/48

I have installed a clean Magento 1.9.2.0, using Akeneo 1.3.18 and PIMGento 1.2.3. I’m exporting products via the Akeneo Enhanced connector and also trying DND connector.

On this new install (using the same csv files as being used in above install), I am having another issue with configurable products. This time, configurable products are not being listed on the Catalog –> Manage Products screen. Nor are they visible on the frontend. However, it appears as though the configurables are being created as when I click on Catalog –> Manage Categories and view the categories products, I can see that the configurable has been created.

However, can’t be viewed under Products tab.

Any help here would be greatly appreciated.

**Comment by magentix** [comment]
Hello,

The problem is than "status" attribute for configurable product is not setted on import. In Pimgento Configuration, set "enabled > 1" for "Default configurable attributes values" option.
(Note: "enabled" attribute must be exported in product CSV file).
