### ISSUE TITLE
Import Categories missing informations

### ISSUE THREAD

**Issue by dominicnguyen810** [Agence-DnD/PIMGento#5]
Hey guys,

Magento ver. 1.14.1.0
I got this issue when trying to import categories

After successful import, category is missing information as name, URL key...
Please view image below for details:
http://s24.postimg.org/cdwfjsnyt/2015_04_20_17_37_36.png

**Comment by dominicnguyen810** [comment]
I have fixed problem.
I have setting channel in Akeneo site is en_AU, so when exported categories from Akeneo, CSV file inserted one column named 'label-en_AU'. I changed it to 'label-en_US' and imported succeccful.

Thanks

**Comment by magentix** [comment]
Hello Dominic,

If Akeneo is set to "en_AU", Magento configuration must specified same language.

1. Store / Website language:
System > Configuration > General > General > Locale Options
Set local option to "English (Australia)"

2. Default admin language:
System > Configuration > Catalog > Pimgento > General
Set "Admin language" option to "en_AU"

Regards,
Matthieu
