### ISSUE TITLE
Unable to match product attributes with "-" separators in key

### ISSUE THREAD

**Issue by linslin** [Agence-DnD/PIMGento#53]
Its not possible to configure matching attributes in the products configure section like. 

#### description-en_EN-ecommerce -> description 

This format (description-en_EN-ecommerce ) is a default behavior of Akeneo and can't be solved without writing an own exporter. Seems like the matching logic does not support this kind of format. Btw. underscores work like a charm. Could you solve this?

**Comment by linslin** [comment]
So, finally there seem to be no support here. I found the problem myself. There is a big logical error in PIMGento @localization here:

```php
if (preg_match('/^(.*)-(.*)$/', $column)) {
   $translation = true;
   ...
```
https://github.com/Agence-DnD/PIMGento/blob/master/app/code/community/Pimgento/Product/Model/Import.php#L521 

While a attribute includes a "-" in key, PIMGento is starting to match attributes as localized (translated). So, I have no clue why this plausibility check could be that wrong. By forcing `$translation = false` everthing works fine. 

But how to do a clean plausibility check if translations/localization is active?

**Comment by magentix** [comment]
Hi,

Not a logical error. From Akeneo, columns can be:

* attribute
* attribute-en_EN
* attribute-channel
* attribute-en_EN-channel

With "description-channel" format, we must translate for all stores associated to website. So we must consider all possible scenarios.

**Comment by linslin** [comment]
@magentix  Oh wow, did you forget to push the close button on that ticket? ;) I'am missing some attributes formats in your answer which are not localized like "PARENT-groups" or like "PRICE-EUR". All this attributes aren't imported because PIMGento try to localize those, but there is nothing to localize. What you think?

**Comment by magentix** [comment]
In Magento configuration (System > Configuration > Pimgento > General), Akeneo channel must be mapping with Magento website (field "Add website mapping").

Have you the same issue with mapping?
