### ISSUE TITLE
Facing Issues while importing the Akeneo products to magento

### ISSUE THREAD

**Issue by yesjosephraja** [Agence-DnD/PIMGento#54]
# pimgento_product
# product_1.csv
[03:50:47] tart task
[03:50:47] Task id: 55d5b10793898
[03:50:47] Create temporary table
[03:50:48] Step completed
[03:50:48] Insert data into temporary table
SQLSTATE[HY000]: General error: 29 File '/home/usbpromos/html/var/import/pim/product_1.csv' not found (Errcode: 13)

I am facing above issue while importing the exported product from Akeneo Any suggestions? I says the file is not found. But i can see the file been uploaded there.  

I exported the products from Spread -> Export Profiles -> csv_product_export

**Comment by mrafulfill** [comment]
This is probably caused because the file you are trying to import is not in a directory which is readable by the user the MySql server is running as. See this post: http://www.electrictoolbox.com/article/mysql/mysqlimport-errors/
and scroll down to "insufficient directory permissions".

**Comment by magentix** [comment]
Hello,

If Mysql server is on different server than Apache, add LOCAL in LOAD DATA request:

Pimgento/Core/Model/Resource/Request.php
```php
255: $query = "LOAD DATA LOCAL INFILE '" . addslashes($file) . "' REPLACE
```

In MySQL, "local_infile" option must be setted to "On":

```shell
SHOW GLOBAL VARIABLES LIKE 'local_infile';
+---------------+-------+
| Variable_name | Value |
+---------------+-------+
| local_infile  | ON    |
+---------------+-------+
1 row in set (0.00 sec)
```

**Comment by yesjosephraja** [comment]
1)
 
I have tried both options.
giving folder permission to folder. magentoroot/var/import/pim/  
Imported a .sql file from the above folder into a mysql db. Didn't tried import from a csv file. But guessing that permission is not a problem


2)
 
Also Tried changing the changes you asked to to do in file and DB
  Pimgento/Core/Model/Resource/Request.php
SHOW GLOBAL VARIABLES LIKE 'local_infile';
+---------------+-------+
| Variable_name | Value |
+---------------+-------+
| local_infile  | ON    |
+---------------+-------+
1 row in set (0.00 sec)

But it gives different error now

# pimgento_product
# product_2.csv
[23:50:59] tart task
[23:50:59] Task id: 55ed33d3b0ac2
[23:50:59] Create temporary table
[23:51:00] Step completed
[23:51:00] Insert data into temporary table
SQLSTATE[42000]: Syntax error or access violation: 1148 The used command is not allowed with this MySQL version

**Comment by gaurav-malhotra** [comment]
yes mysql is restricted by apparmor, I have strugled whole day to figure it out. Finally I found to disable mysql profile from apparmor. Just run this command in putty

apparmor_parser -R /etc/apparmor.d/usr.sbin.mysqld

**Comment by sition** [comment]
better:

SQLSTATE[HY000]: General error: 29 File '/your uploaded file' not found (Errcode: 13)

on ubuntu 16:
> sudo nano /etc/apparmor.d/usr.sbin.mysqld

add the line 
# Allow temp dir access for mysql 
 /tmp/** rwk,


> sudo /etc/init.d/apparmor reload
