### ISSUE TITLE
Productimport - Step: Reindex causes SQL-Error

### ISSUE THREAD

**Issue by linslin** [Agence-DnD/PIMGento#55]
Hey, while importing products a SQL Error comes up. This happens at step: "reindex":

SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`mage-test`.`#sql-501_3dbb`, CONSTRAINT `FK_CAT_PRD_FLAT_1_ENTT_ID_CAT_PRD_ENTT_ENTT_ID` FOREIGN KEY (`entity_id`) REFERENCES `catalog_product_entity` (`entity_id`) ON DELETE CASCADE ON UPDATE)

What should I do?

**Comment by magentix** [comment]
Hello,

For this error, truncate all Magento tables prefixed by "catalog_product_flat_"

Example:

```sql
TRUNCATE catalog_product_flat_1;
TRUNCATE catalog_product_flat_2;
```
