### ISSUE TITLE
Default TAX attribute on product is not updating 

### ISSUE THREAD

**Issue by linslin** [Agence-DnD/PIMGento#57]
The TAX Attribute setup at PIMGento - Products does not update existing products. It only effects new products. I can't change the TAX class on a running system so. Could you solve that?

**Comment by magentix** [comment]
Hello,

This is fixed in last release. Tax Class Id is now updated on existing products.

**Comment by linslin** [comment]
I'm using the latest version of PIMGento with Magento 1.9.0.1, TAXES do not update. Did you test that? Please reopen.
