### ISSUE TITLE
Import Attributes Error

### ISSUE THREAD

**Issue by dominicnguyen810** [Agence-DnD/PIMGento#6]
Hey guys,

Magento ver. 1.14.1.0
I got this issue when trying to import attribute

#pimgento_attribute
#attributes.csv
[03:42:09] tart task
[03:42:09] Task id: 5534d80179e09
[03:42:09] Create temporary table
14 columns excepted, 13 given

Thanks!

**Comment by manh-nguyen** [comment]
## csv sample 

    type;code;label-en_US;label-fr_FR;group;unique;useable_as_grid_filter;allowed_extensions;metric_family;default_metric_unit;localizable;scopable;families
    pim_catalog_identifier;sku;SKU;SKU;general;1;1;;;;0;0;Cards_Or_Blind_Box,Decks,Default,LIGHTSPEED_PRODUCT_ATTRIBUTE_SET,TShirts
    pim_catalog_text;name;[name];[name];general;0;0;;;;1;1;Cards_Or_Blind_Box,Decks,Default,LIGHTSPEED_PRODUCT_ATTRIBUTE_SET,TShirts

I saw you fixed 14 columns in code but the generated file from Akeneo has 13 columns only

Please check it.

**Comment by DnD-Mimosa** [comment]
Manh,

If you are on Akeneo PIM 1.3, the column usable_as_grid_column has been removed.

To fix the problem, you have to change app > code > community > Pimgento > Attribute > Model > Import.php on line 27 :

$this->getRequest()->createTableFromFile($this->getCode(), $file, 14);

should be replace by :

$this->getRequest()->createTableFromFile($this->getCode(), $file, 13);

Regards,
Florian.

**Comment by manh-nguyen** [comment]
Thank you Mimosa. I just did it manually and it was working.

Cheers,
Manh
