### ISSUE TITLE
incorrect updates on "created_at" and "updated_at" fields in Magento DB

### ISSUE THREAD

**Issue by mrafulfill** [Agence-DnD/PIMGento#60]
"created_at" and "updated_at" fields in Magento table catolog_product_entity are always updated on Pimgento product import. We understand the need for this on the "updated_at" field, but this should not happen with the "created_at" field if the SKU already exists in the Magento DB? We use both fields to selectively trigger export from Magento to our ERP system.

**Comment by ToonSpinISAAC** [comment]
Looking through the code: the same thing probably happens to categories.

**Comment by magentix** [comment]
Hi,

Thanks for report and fix. This issue have been fixed in last commit.

**Comment by lazyguru** [comment]
That's great.  Can I ask why you didn't just accept my PR instead of committing the exact code I provided yourself?

**Comment by magentix** [comment]
Hi lazyguru,

Your code is great, i've juste reformatted it with an "array_keys" function. It shortens the method :)

**Comment by lazyguru** [comment]
Ah, ok.  I missed that.  Thanks
