### ISSUE TITLE
Attribute entity matching is wrong

### ISSUE THREAD

**Issue by linslin** [Agence-DnD/PIMGento#62]
Attribute matching in `product import` is logical wrong. Currently its matching `AkeneoAttributeValue with MagentoAttributeValueID`. It should match `AkeneoAttributeValue with MagentoAttributeValue` instead of the MagentoAttributeValueID (which is unknown to Akeneo..).

**Comment by magentix** [comment]
What do you mean with "MagentoAttributeValueID" ?

Akeneo attributes have a code. In Magento, attributes have code and identifier. On product import, we match Akeneo code with Magento attribute, and we dispatch data in EAV structure (attribute_id, entity_id, store_id, value).

**Comment by linslin** [comment]
PIMGent is matching AkeneoImportValue with `eav_attribute_option_value.option_id` instead of matching  AkeneoImportValue with `eav_attribute_option_value.value` .

**Comment by linslin** [comment]
@magentix Any news on this?

**Comment by magentix** [comment]
Hi linslin,

I commit a fix on it. Options was not correctly matched on localizable or scopable attribute (like size-en_US). Look at this commit :)

https://github.com/Agence-DnD/PIMGento/commit/d10b95d260f438cee7d6e959448861e2f52d5d12
