### ISSUE TITLE
Facing Issues while importing the Akeneo products to magento

### ISSUE THREAD

**Issue by premkumarr-smackcoders** [Agence-DnD/PIMGento#63]
This is to reopen issue id 54,
I'm working on to import Akeneo products to magento, I face below issue

[03:50:47] tart task
[03:50:47] Task id: 55d5b10793898
[03:50:47] Create temporary table
[03:50:48] Step completed
[03:50:48] Insert data into temporary table
SQLSTATE[HY000]: General error: 29 File '/home/usbpromos/html/var/import/pim/product_1.csv' not found (Errcode: 13)

I am facing above issue while importing the exported product from Akeneo Any suggestions? I says the file is not found. But i can see the file been uploaded there.

You suggested me to provide permissions, still I cant get it work

Here is the issue after providing file permissions
 

1)

I have tried both options.
giving folder permission to folder. magentoroot/var/import/pim/

Imported a .sql file from the above folder into a mysql db. Didn't tried import from a csv file. But guessing that permission is not a problem

2)

Also Tried changing the changes you asked to to do in file and DB
Pimgento/Core/Model/Resource/Request.php
SHOW GLOBAL VARIABLES LIKE 'local_infile';
+---------------+-------+
| Variable_name | Value |
+---------------+-------+
| local_infile | ON |
+---------------+-------+
1 row in set (0.00 sec)

But it gives different error now

pimgento_product
product_2.csv
[23:50:59] tart task
[23:50:59] Task id: 55ed33d3b0ac2
[23:50:59] Create temporary table
[23:51:00] Step completed
[23:51:00] Insert data into temporary table
SQLSTATE[42000]: Syntax error or access violation: 1148 The used command is not allowed with this MySQL version

**Comment by lazyguru** [comment]
Your error is right there in the last line:

    SQLSTATE[42000]: Syntax error or access violation: 1148 The used command is not allowed with this MySQL version

What version of MySQL are you running?

**Comment by magentix** [comment]
Hi,

**LOAD DATA INFILE:** MySQL get file on MySQL server. If Apache is not on the same server than MySQL, you will get: "13 Can't get stat of '...' (Errcode: 2 - No such file or directory)"

**LOAD DATA LOCAL INFILE:** In this case, Apache and MySQL can be on different servers, but "local_infile" variable must be setted to "ON", otherwise you will get "1148 The used command is not allowed with this MySQL version"

In these 2 cases, MySQL user must have "FILE" rights
