### ISSUE TITLE
Product URL is not made during the import

### ISSUE THREAD

**Issue by AlexanderHuyghebaert** [Agence-DnD/PIMGento#64]
When adding or updating new products from the CSV that is generated out of Akeneo, the import doesn't make an product url...
How can this be fixed?
We have 4 languages for every product, and url needs to be the auto generated url of the name

**Comment by magentix** [comment]
URL are not automatically generated by Pimgento. We work on this issue.

Most of the time the URL key is managed directly in akeneo (attribute url_key) and exported to Magento, but we must find an alternative.

**Comment by nbinnendijk** [comment]
Hi Magentix, if url_key is managed in Akeneo, and imported by PIMgento, how does PIMgento manage to avoid duplicates for Configurables products created based on groups.

I.e. : as the configurable product attribute are created from the attributes of the first simple product of the group, initializing configurable product url_key from first simple product url_key would end into a duplicate url_key eror, no ?

**Comment by magentix** [comment]
Hello nbinnendijk,

In Pimgento configuration (system > Configuration > Pimgento > Product), you can set in "Default configurable attributes values":

* url_key > LOWER(CONCAT(`url_key`,"-",`groups`))

This will create: **simple-product-1-url-key-my-group**

**Comment by nbinnendijk** [comment]
thx for  the tip :-)

**Comment by AlexanderHuyghebaert** [comment]
Is there an update when this will be fixed when no url key is managed in Akeneo?
Because this is default functionality from Magento that a new URL is created if the name changes.

This is also in your description of the extension...

**Comment by AlexanderHuyghebaert** [comment]
Hello, 

this is becoming quite urgent now!
Is there already an update about this?

**Comment by AlexanderHuyghebaert** [comment]
@magentix,
We encounter an other issue:
When we set up the url_key in Akeneo and let it import like you say (Strange because normally Magento should manage the url_keys), there is an id (of the store) added to the url. So for each store we have a duplicate url.
When we change the url, there is no redirection made from it (when we do this in Magento, it automatically generates a redirect). 
Could you please check this?

**Comment by AlexanderHuyghebaert** [comment]
Why is this closed? This is not fixed yet!

**Comment by magentix** [comment]
Hi,

We now have "Add store to URL key" option in Pimgento configuration (System > Configuration > Pimgento > Product).

Redirection are made on "catalog_url" index. Try to manually update an url key in catalog_product_entity_varchar table and reindex. Old URL will be automatically redirect to new.

Example:

```sql
UPDATE catalog_product_entity_varchar SET value = 'new-test' WHERE value = 'old-url' AND attribute_id = 97;
```

```shell
php indexer.php -- --reindex catalog_url
```
