### ISSUE TITLE
How to handle CrossSeller

### ISSUE THREAD

**Issue by linslin** [Agence-DnD/PIMGento#65]
Is there a way to import xSeller with PIMGento?

**Comment by magentix** [comment]
Hi linslin,

In product import, step 16 is: "Update related, up-sell and cross-sell products".

In this step we are looking for "RELATED-products", "UPSELL-products" and "CROSSSELL-products" columns in CSV file.

These columns have products sku separated by semicolon.

**Comment by nik736** [comment]
What could be the reason if these things don't get imported? In my CSV there are Crossell IDs but they wont show up in Magento backend. Do I need to setup something in PIMGento settings?
