### ISSUE TITLE
utf8 encoding issue on import

### ISSUE THREAD

**Issue by dhsl** [Agence-DnD/PIMGento#67]
Hi Agence-DnD,

i got a problem when trying to import a UTF-8 encoded .csv. It was generated by your Akeneo-Plugin.

Database is already set to utf8_general_ci. File is also valid UTF-8 encoded. German umlauts still get messed up, so ä becomes Ã¤ for example.

Do you have a clue where I may look for the problem? I'm using the current stable tag 1.0.3 with Magento 1.9.1.0.

**Comment by roman204** [comment]
Hi,

is there a solution until now? running into the same problem...

**Comment by dhsl** [comment]
Hi Roman,

I’m working around it by correcting the wrong encoding directly in my database.
This is the MySQL query I use:
UPDATE `catalog_product_entity_text` SET `value` = CONVERT(CAST(CONVERT(`value` USING latin1) AS BINARY) USING utf8)

Did you make sure that your database is configured to use utf8?

--  
Daniel Henschel

**Comment by roman204** [comment]
yes i did, but i found out that the "LOAD DATA..." query has no "character set"... inserted it right now and report after test...

**Comment by roman204** [comment]
hmm no you were right the the encoding of the database was not set to utf8

**Comment by roman204** [comment]
after changing the enconding it works! thanks.

**Comment by dhsl** [comment]
Great to hear that and happy I could help.

@AgenceDnD, maybe you could add that to your FAQ or somewhere else, where others can find it and work around the problem.

**Comment by magentix** [comment]
Hi dhsl,

Thank you for your answer. This tip will be added to Readme.

**Comment by dhsl** [comment]
Hi magentix,

I would be happy if you could fix that issue directly. My current problem is that I have no simple solution to running that sql query directly after running the pimgento import.
