### ISSUE TITLE
Admin Language: use global settings instead if own config

### ISSUE THREAD

**Issue by alexkazik** [Agence-DnD/PIMGento#68]
Drop "System > Configuration > Catalog > Pimgento > General : Admin language" and use "System > Configuration > (Scope: Default Config) -> General > General > Locale Options : Locale".

Which would lead to replacing `Mage::getStoreConfig('pimdata/general/admin_lang')` by `Mage::getStoreConfig('general/locale/code', 'admin')` and removing the configuration option.

**Comment by magentix** [comment]
Hi alexkazik,

We update this in last commit : https://github.com/Agence-DnD/PIMGento/commit/7d89d061ed74a0159b3b4cbde2b7faf98e97ab28
