### ISSUE TITLE
Import related group from Pim to Magento

### ISSUE THREAD

**Issue by dominicnguyen810** [Agence-DnD/PIMGento#7]
Hey guys,

I have created product related group in Akeneo Pim
![1](https://cloud.githubusercontent.com/assets/10016971/7292250/58d4cc6c-e9c4-11e4-83a7-c56be5cae57d.png)

 and import to Magento, it changed to Configurable Product.
![2](https://cloud.githubusercontent.com/assets/10016971/7292251/5bfa4958-e9c4-11e4-89eb-973542a264c0.png)

How to fix it.

Thanks!

**Comment by magentix** [comment]
Hello,

Group feature is actually used for create configurable products. Products in group create in Magento a new configurable products with specified products as simple.
