### ISSUE TITLE
Localized attribute simple select option is not updated on product import

### ISSUE THREAD

**Issue by bhouillon** [Agence-DnD/PIMGento#72]
Hi, thanks for Pimgento, you are doing a great job,
When I import products, localized options are not set.
For example, in my products.csv I have :
vat-fr_FR;vat-fr_LU
tva;tva_lu 
It's a feature not yet implemented or this is an issue ?

Thanks in advance, 
Regards,
Benjamin

**Comment by magentix** [comment]
Hi Benjamin,

Is attribute "vat" a select or multi-select attribute type ?

**Comment by magentix** [comment]
This issue has been fixed.
