### ISSUE TITLE
No replication of simple product data on configurable product

### ISSUE THREAD

**Issue by racol66** [Agence-DnD/PIMGento#74]
Hello,

I have imported a product with groups column. It's create two products, one configurable and a second simple correctly associated. The simple product data are correct (description, name, color, etc) but the configurable product is empty (there is just the sku). 

However, in Pimgento configuration, "Default configurable attributes values" is empty (" Leave empty to retrieve the value of the first simple product").

Is it a bug, or I miss something ?

thank you in advance !

**Comment by DnD-Mimosa** [comment]
Hi @racol66,

In Default configurable attributes values, you just have to set the attributes code that you want to have in your configurable product.

If you leave the value blank, it will take the simple product attribute value but if you set a value, it will take this one.

I hope it helps.

Regards,
Florian.

**Comment by racol66** [comment]
Hi @DnD-Mimosa 

Thank for your answer !

Ok, It's work :) ! to avoid misunderstandings, it is necessary to specify attribute code in Pim attribute field and let the value field empty.

Thank you !

**Comment by dardanKG** [comment]
Hi @racol66 

Do you have a sample csv file that creates a configurable product? for me it just seems to create a simple product even though I specify to create a configurable.
