### ISSUE TITLE
How to create Variant Export CSV on Akeneo side to Import it in Magento with Pimgento 

### ISSUE THREAD

**Issue by VianneyduG** [Agence-DnD/PIMGento#76]
Hi,

I tried to find the way to export Variant Group from Akeneo with DND job but i can't create this type of job.
When on the Magento/Pimgento side i'm able to import it...

Does somebody have an idea...

Which export profile may i use?

Thanks a lot :)

**Comment by Nik736** [comment]
Hi,

have you found a solution for this? I am looking for the same.

**Comment by DnD-Mimosa** [comment]
Hi,

We did not created this export on Akeneo side. The solution is to use Akeneo Variant group export and to import the file manually (you can also set a cron job which will send the file on your remote server, with rsync command for example).

If you upgrade your Akeneo PIM to 1.4 version, you will have to use Akeneo EnhancedConnectorBundle (https://github.com/akeneo-labs/EnhancedConnectorBundle).

In fact, Dn'D will not support anymore the bundle on Akeneo side, only PIMGento.

Regards,
Florian.

**Comment by Nik736** [comment]
Hi Florian,

thanks for the fast answer. Is there any example screenshot or explanation how the PIMGento product settings could look like? I found a webinar but there was not talked about products with "Create configurable" -> Yes?

**Comment by Nik736** [comment]
I installed Akeneo 1.4 now, but still this is not working:
http://www.akeneo.com/forums/topic/variant-groups-magento/

**Comment by ravitechrlabs** [comment]
Hi. after creating variant groups in Akeneo and exporting as csv using Akeneo Variant Group export, I used Pimgento to import the variant group into Magento, but there is no configurable product created.

**Comment by magentix** [comment]
Hi,

Variant import only save in database the attributes to use with configurable products. Configurable will be created in product import.

**Comment by nik736** [comment]
Hi magentix, what could be the issue if there is no configurable product in the back-office? I created everything in Akeneo, I think the problem is that I make something wrong at the import stage, but don't know what :D
