### ISSUE TITLE
Import task is failing

### ISSUE THREAD

**Issue by adamjamesmartin** [Agence-DnD/PIMGento#8]
I am trying to run a test import for categories. It keeps failing at the same place:

        # pimgento_category
    # categories_1.csv
    [23:51:51] Start task
    [23:51:51] Task id: 553b398735f89
    [23:51:51] Create temporary table
    [23:51:51] Step completed
    [23:51:51] Insert data into temporary table
    SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Name or service not known

Any ideas?

**Comment by adamjamesmartin** [comment]
looking at the pimgento.log - I am getting the following:

    Cannot create table without columns comments

**Comment by adamjamesmartin** [comment]
I tried changing the host (in local.xml) from a socket to localhost and then got user permission denied. But only for the PIM. all other aspects of magento work fine. So for some reason, the PIM import is not able to access the database correctly. I am at a bit of a loss.

**Comment by adamjamesmartin** [comment]
Tried on a different host with the same issue. So I have now tried on Google Cloud (via bitnami) and DigitalOcean.

**Comment by adamjamesmartin** [comment]
Ok. So I found the issue. the mysql user needs to have FILE permission. But this is not really good because FILE permission is global.

**Comment by sammarcus** [comment]
@adamjamesmartin How specifically did you change this? I am having the same issue. Thanks!
