### ISSUE TITLE
Import multiple websites

### ISSUE THREAD

**Issue by kodea** [Agence-DnD/PIMGento#80]
Hello,

I am trying to use the module to import products into 2 Magento websites, and I don't get how to do it.
- In Akeneo, I can set the websites into separate canals, and generate 1 file per canal
- But in Magento, I don't see how to import separate files, the configuration of the file paths is global.

I guess I could give the same path to the files from different canals, generate them at different moments, and time the import carefully in order to make it work, but this seems risky.

Could you please tell me how this is intented to work?

**Comment by magentix** [comment]
Hello kodea,

When you export into separate canals in Akeneo, it will generate colums with canal code, example:

* **Export 1:** description-canal1
* **Export 2:** description-canal2

In export 1, description will be setted for all stores of canal1.

If attribute is localizable, you will get:

* **Export 1:** description-en_US-canal1;description-de_DE-canal1
* **Export 2:** description-en_US-canal2;description-de_DE-canal2

In export 1, description will be setted for all stores of canal1 with en_US (description-en_US-canal1) and de_DE (description-de_DE-canal1) langages.

In Magento, match canal with website in Pimgento Configuration (System > Configuration > Pimgento > General). Example:

* canal1 > website1

For Cron configuration, you must set files with semicolon : export-canal1.csv;export-canal2.csv
