### ISSUE TITLE
installer_data minimal does not work on 1.4

### ISSUE THREAD

**Issue by akkermanronald** [Agence-DnD/PIMGento#81]
After a clean composer install of 1.4.3 Akeneo on a clean Ubuntu 14.04 instance with installation parameter set at "PimInstallerBundle:minimal" we are unable to create families, attributes, products, etc. 

After pressing the "create ..." button the screen will hang forever and nothing will happen. When relaunching the same install with demo data with the php app/console pim:installer:db --env=prod command everything works fine and new families etc. can be created as expected.

Returning to minimal thereafter results in the same issue. Is there something in the minimal data creation which is not compatible with 1.4? 

Regards
Ronald

**Comment by DnD-Fute** [comment]
N

-- 

Agence Dn'D
Digital & Dynamic Agency

23, rue Edmond Nocard - 94410 Saint Maurice
Tél. : +33 1 48 75 59 59
www.dnd.fr / @D_n_D

**Comment by akkermanronald** [comment]
Sorry this issue should have been posted on Github Akeneo. I will post it there now and this issue can be closed.
