### ISSUE TITLE
Deleted products in Akeneo stay in Magento

### ISSUE THREAD

**Issue by AlexanderHuyghebaert** [Agence-DnD/PIMGento#83]
When a product is deleted in Akeneo, it stays in Magento.
Is there an update when this will be fixed?

This is definitely a blocking issue.

**Comment by arnosledsens** [comment]
Same issue. Any updates yet?

**Comment by bubbleshop** [comment]
+1

**Comment by jreinke** [comment]
+1

**Comment by magentix** [comment]
Hi,

Synchronization for deleted data in Akeneo (categories, products, attributes...) is not yet implemented. We work on a solution for deleting.
