### ISSUE TITLE
Importing option where the code contains the code of the attribute does not work

### ISSUE THREAD

**Issue by nbinnendijk** [Agence-DnD/PIMGento#84]
Hi,

FYI.

Ex:
if Attribute code is "toto"
if option code is "toto_value1"
then on product import, the product attribute value will not be initialized, instead of being initialized with toto_value1

Workaround we applied: do not have option code  that contains attribut code

**Comment by magentix** [comment]
Hi,

We have tested with color attribute:

We have added "color_blue" option for attribute "color". Option have been setted to product.

So we fail to reproduce this issue...
