### ISSUE TITLE
csv file not found

### ISSUE THREAD

**Issue by adamjamesmartin** [Agence-DnD/PIMGento#9]
I see you closed another issue the same as mine. Except I am not using windows.

    SQLSTATE[HY000]: General error: 29 File '/var/www/html/magento/var/import/pim/categories_1.csv' not found (Errcode: 13)

I have confirmed the file is there. And I have used the files from 1.0.1 release.

**Comment by adamjamesmartin** [comment]
This issue was found. Apparmor was restricting access.

**Comment by christophednd** [comment]
OK, 
i close this issue.

**Comment by cyril1909** [comment]
yes mysql is restricted by apparmor, I have strugled whole day to figure it out. Finally I found to disable mysql profile from apparmor. Just run this command in putty

 apparmor_parser -R /etc/apparmor.d/usr.sbin.mysqld
