### ISSUE TITLE
configure default visibility in Pimgento admin settings

### ISSUE THREAD

**Issue by akkermanronald** [Agence-DnD/PIMGento#90]
It would be great if it was possible to configure the default visibility of products in the Pimgento admin settings. Currently we have changed this in the product import.php to value 1, which equals "not visible individually", as we want to selectively make products visible in each store view, depending on a number of conditions. If the default value is set to 4 by Pimgento, this will be inherited by all other storeviews so long as "use default values" is still ticked. By reversing the default to 1 we are better able to selectively "activitate" the visibility  for each store view. As different users may have different preferences / requirements it would be great if this would be pulled from configuration setting rather than hard coded.

We have tested re-import of the same products with the current Pimgento code and this respects any values set on store view level in the Magento admin, which is great!

**Comment by DnD-Hellion** [comment]
Hi @akkermanronald ,
As it is an old propositon and has not been supported, we close this issue.
Best regards,
