### ISSUE TITLE
Unable to create the Configurable products - "Update configurable prices - Got SQL error"

### ISSUE THREAD

**Issue by ewallteam** [Agence-DnD/PIMGento#91]
Hi All,

We got the SQL syntax error while importing the products CSV, which was exported by Enhanced Connector bundle. See the below link for the screenshot. Kindly help us to migrate the products from Akeneo to Magento.

https://drive.google.com/file/d/0B8aStV7rYyB6ZmRRLWRpbjhtdXM/view?usp=drivesdk

Thanks,
Ewall Team.

**Comment by dardanKG** [comment]
That happens when you haven't selected an attribute to be used as a configurable. Go to pimgento settings > products tab > and select an attribute in the 'configurable attributes' bit (size, or colour etc).

**Comment by dardanKG** [comment]
It's a bug in the product Import class, line 875:

        $attributes = explode(',', $this->getConfig('configurable_attributes'));

        if (count($attributes) && $priceId && $specialPriceId) {

If no attribute is selected, $attributes is "", which passes the count() check when it shouldn't.

**Comment by ewallteam** [comment]
Thanks @dardanKG  
Now I have assigned the configurable attributes and the import was completed. But there is no configurable products listed in the Manage Products Grid. When I have inspected deeply in database level there are some configurable products are created in DB but the magento failed to list them.

see the below link for screenshot
In DB  https://drive.google.com/file/d/0B8aStV7rYyB6UGx0Q3M5MllwSms/view?usp=drivesdk
any Idea? ;-(

**Comment by dardanKG** [comment]
I think that has to do with the visibility setting. In the Pimgento settings, under the 'Default configurable attributes values' add pim attribute: 'enabled' to value 1 and try importing them again.

**Comment by ewallteam** [comment]
Thanks @dardanKG  now I can see all the Configurable products in my magento but unluckily their name seems to be blank. May I need to create any custom mapping to import the name?

**Comment by dardanKG** [comment]
Yes. Under the 'Default configurable attributes values' option, you have to map all of the attributes your simple products have, with a blank value field. When pimgento creates a configurable product, it takes the first simple product and copies its attribute values to the configurable, but only if the attribute is listed in the pimgento setting.

**Comment by ewallteam** [comment]
I appreciate your support @dardanKG . Now my configurable products are imported correctly. Can you please let me know Is it possible to create the bundle products in akeneo? If yes then this extension could import bundle products?

**Comment by dardanKG** [comment]
To be honest I don't know what bundle products are, but this forum post might help: http://www.akeneo.com/forums/topic/bundle-products/

**Comment by ewallteam** [comment]
Many Thanks for your support, @dardanKG. I will close this issue.
