### ISSUE TITLE
tax_class_id options created in Magento

### ISSUE THREAD

**Issue by akkermanronald** [Agence-DnD/PIMGento#92]
The option values for tax_class_id should not be imported in Magento with the option import. The option values should remain empty as below:

![schermafdruk 2015-10-26 12 58 37](https://cloud.githubusercontent.com/assets/15016164/10728388/a1542f14-7be1-11e5-9668-aa960a4f9af3.png)

If the options are created this results in faulty tax_class for products imported thereafter. Any suggestions how we can solve this?

**Comment by akkermanronald** [comment]
Some additional information; which I am sure is not new to you. Magento has the tax_class_id's stored in the tax class table like so:

<img width="294" alt="schermafdruk 2015-10-27 13 31 19" src="https://cloud.githubusercontent.com/assets/15016164/10758052/237561a2-7caf-11e5-9c6a-975bc38fe122.png">

After Pimgento option import in Magento the options for tax_class_id are created as regular attribute options, see also my original post. After remvoing these options we kept facing the issue that products where not being assinged the correct tax_class_id, despite the correct value in the products.csv. 

After a long search we found that the option_id for the newly created tax_class_id attribute options had been assinged in the Pimgento_code table:

<img width="362" alt="schermafdruk 2015-10-27 13 34 49" src="https://cloud.githubusercontent.com/assets/15016164/10758116/95f9dc30-7caf-11e5-8b1d-9a5819e68257.png">

Although the Pimgento option import works absolutely fine, it is crucial to eliminate the creation of options for the tax_class_id attribute in Magento. Is there an easy way to ingore the tax_class_id attribute options being created or should we post this as an Akeneo issue, since the creation of the option.csv is now handled with native Akeneo option export?

**Comment by magentix** [comment]
Ho akkermanronald,

"tax_class_id" can be easily ignored in Pimgento configuration:

System > Configuration > Pimgento > Attributes > PIM code exclusion

Add here attribute code you want to ignore.

**Comment by akkermanronald** [comment]
Hi Magentix,

Will this eliminate the option import for the tax_class_id? 
We do need to be able to import the tax_class_id values with the product import. 

Regards
Ronald

**Comment by magentix** [comment]
You should ignore options for "tax_class_id" attributes.

However, in "System > Configuration > Pimgento > Options > PIM code exclusion", you must add option_code, not attribute code.

For exemple, if option code is "tax_2" in option CSV export, add "tax_2" in this field.

**Comment by akkermanronald** [comment]
Ok, many thanks for clarifying!
