### ISSUE TITLE
Bundled Products 

### ISSUE THREAD

**Issue by jamstew2001** [Agence-DnD/PIMGento#93]
Hi DND Team

Are you able to add the function to export bundled products into Magento. 
We sell chairs
We have any bundled products. 
The bundled products are chairs that have share components. These components need to be stocked individually because they are shared. 
For example a chair has a top and base there are 10 different colour tops and 10 different colour bases. If I had a normal configurable product with simple products I would need to stock 100 chairs to be able to offer 1 chair in every colour and I would need 100 simple products. However, with a bundled product I am able to stock 10 tops and 10 bases but I can offer the customer all 100 variants because the bases and tops are stocked individually. 

To give you an example these two products have multiple colour tops and bases. instead of having to stock every colour in every combination we can stock 10 of each tops and 10 of each base but means we can do every combination. In these examples also the chairs share them same tops and just hav different bases. 

http://www.swiveluk.com/uk/charles-eames-style-dsw-fibreglass-dining-chair.html

http://www.swiveluk.com/uk/charles-eames-style-dsw-fibreglass-barstool-with-swivel.html?

Many thanks

James

**Comment by DnD-Hellion** [comment]
Hi @jamstew2001 ,
As it is an old propositon and has not been supported, we close this issue.
Best regards,
