### ISSUE TITLE
Categories synchronization not effective ?

### ISSUE THREAD

**Issue by bhouillon** [Agence-DnD/PIMGento#96]
Hi & thanks for PIMGento.
I'm wondering if PIMGento can handle categories synchronization, because, when I delete a category in Akeneo, after import it isn't delete on Magento, is it a normal behavior or is there a configuration to do ?
Regards

**Comment by magentix** [comment]
Hi,

Synchronization for deleted data in Akeneo (categories, products, attributes...) is not yet implemented. We work on a solution for deleting.

**Comment by akkermanronald** [comment]
Hi Magentix, 

Deletion would be a great function but should be a configureable setting? In our scenario we would not want to delete. 

On the category issue above I am not 100% if bhoullion means the deletetion of a product allocation to a category or to delete the entiry category?

We are facing the issue that the product allocation to categories is not being updated when a product is removed from a category in Akeneo. The other way around works fine, if we add a product in Akeneo to an additional category this get's added in Magento. We can create a separate issue for this if that makes sense, but perhaps we are talking about the same issue as bhoullion. 

Regards
Ronald
