### ISSUE TITLE
Status of pull requests

### ISSUE THREAD

**Issue by buttash** [Agence-DnD/PIMGento#97]
Hi
I am using Pimgento in shared hosting environment that doesn't allow MySql access to files.  Hence I decided to write a modification to let me import from csv files without using Load Data Infile.  This modification is pull request #79.  

I was wondering what your policy is towards pull requests in general and mine in particular.  I'm happy to maintain my change on my own branch, but I think given the issues posted here to do with file permissions et al that the option load from a file direct has merit (if only for testing).

As my product database is small I do not have the requirement for a high performance import mechanism so would rather have the option to use the shared hosting environment and a slower import process.

Best
Martin

**Comment by magentix** [comment]
Hi Martin,

We added your pull request yesterday, it's great. Thanks a lot for your contribution !
