### ISSUE TITLE
Family & Attribute import fails when you have default family in Akeneo

### ISSUE THREAD

**Issue by amitvkhajanchi** [Agence-DnD/PIMGento#98]
I have solved this problem, but I thought I will share the issues I have had.  I have "default" family in Akeneo.  When I use the family import, the import of family fails midway and never completes in PimGento.  Once I reimport again, it seems to finish.  What is happening behind the scenes is that a new 'default' entity is created in pimgento_code table that then creates issues when importing attributes in next phase.  All this needs to be manually fixed in the database using mysql.

Either Pimgento needs to have logic to match akeneo's default family to magento's default family, or it should be noted as caution not to use 'default' as code in Akeneo's family.

**Comment by amitvkhajanchi** [comment]
Another issue I have encountered is that if you have custom Attribute Groups you created in Akeneo, its best to create these groups in Magento under Default attribute set.  Otherwise, during Attribute import it fails as the import fails to find the relevant attribute group name.

**Comment by magentix** [comment]
Hi,

You're right, if "Default" label is used in Akeneo, import will fail.

On import, we create a new attribute set id for "Default", but it is impossible to have 2 groups with the same name in Magento.

We can check if "Default" label is used in Akeneo, but default group can be renamed in Magento. In this case, a new group "Default" will be created from Akeneo, it will be confusing...

We are going to work on a solution.
